
# This file is automatically generated, you probably don't want to edit this

advancedReliabilityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "advancedReliabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            secondOrder = FALSE,
            itemType = "auto",
            estimator = "auto",
            missingData = "listwise",
            factors = list(
                list(label="Factor 1", vars=list())),
            showPlots = TRUE,
            plotStyle = "gray",
            reportLang = "en", ...) {

            super$initialize(
                package="fiabilitylab",
                name="advancedReliability",
                requiresData=TRUE,
                ...)

            private$..secondOrder <- jmvcore::OptionBool$new(
                "secondOrder",
                secondOrder,
                default=FALSE)
            private$..itemType <- jmvcore::OptionList$new(
                "itemType",
                itemType,
                options=list(
                    "auto",
                    "continuous",
                    "ordinal"),
                default="auto")
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "auto",
                    "ml",
                    "mlr",
                    "wlsmv"),
                default="auto")
            private$..missingData <- jmvcore::OptionList$new(
                "missingData",
                missingData,
                options=list(
                    "listwise",
                    "fiml"),
                default="listwise")
            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(
                    list(label="Factor 1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric")))))
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "light",
                    "gray",
                    "linedraw",
                    "greenred",
                    "purpleorange",
                    "bluegreen"),
                default="gray")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")

            self$.addOption(private$..secondOrder)
            self$.addOption(private$..itemType)
            self$.addOption(private$..estimator)
            self$.addOption(private$..missingData)
            self$.addOption(private$..factors)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        secondOrder = function() private$..secondOrder$value,
        itemType = function() private$..itemType$value,
        estimator = function() private$..estimator$value,
        missingData = function() private$..missingData$value,
        factors = function() private$..factors$value,
        showPlots = function() private$..showPlots$value,
        plotStyle = function() private$..plotStyle$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..secondOrder = NA,
        ..itemType = NA,
        ..estimator = NA,
        ..missingData = NA,
        ..factors = NA,
        ..showPlots = NA,
        ..plotStyle = NA,
        ..reportLang = NA)
)

advancedReliabilityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "advancedReliabilityResults",
    inherit = jmvcore::Group,
    active = list(
        fitTable = function() private$.items[["fitTable"]],
        fitNote = function() private$.items[["fitNote"]],
        solutionDiagnosticsTable = function() private$.items[["solutionDiagnosticsTable"]],
        solutionDiagnosticsNote = function() private$.items[["solutionDiagnosticsNote"]],
        modelComparisonTable = function() private$.items[["modelComparisonTable"]],
        modelComparisonNote = function() private$.items[["modelComparisonNote"]],
        plotFitComparison = function() private$.items[["plotFitComparison"]],
        plotFitComparisonNote = function() private$.items[["plotFitComparisonNote"]],
        reliabilityTable = function() private$.items[["reliabilityTable"]],
        reliabilityNote = function() private$.items[["reliabilityNote"]],
        plotComparison = function() private$.items[["plotComparison"]],
        plotComparisonNote = function() private$.items[["plotComparisonNote"]],
        plotLoadings = function() private$.items[["plotLoadings"]],
        plotLoadingsNote = function() private$.items[["plotLoadingsNote"]],
        htmtTable = function() private$.items[["htmtTable"]],
        htmtNote = function() private$.items[["htmtNote"]],
        omegaHNote = function() private$.items[["omegaHNote"]],
        modificationIndicesTable = function() private$.items[["modificationIndicesTable"]],
        modificationIndicesNote = function() private$.items[["modificationIndicesNote"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Advanced Reliability (SEM)")
            self$add(jmvcore::Table$new(
                options=options,
                name="fitTable",
                title="Confirmatory Factor Model Fit",
                rows=0,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number", 
                        `format`="zto,digits=2"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="cfi", 
                        `title`="CFI", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="tli", 
                        `title`="TLI", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rmsea", 
                        `title`="RMSEA", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rmsea_ci", 
                        `title`="RMSEA 90% CI", 
                        `type`="text"),
                    list(
                        `name`="srmr", 
                        `title`="SRMR", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="aic", 
                        `title`="AIC", 
                        `type`="number", 
                        `format`="zto,digits=1"),
                    list(
                        `name`="bic", 
                        `title`="BIC", 
                        `type`="number", 
                        `format`="zto,digits=1"),
                    list(
                        `name`="cfi_robust", 
                        `title`="CFI (robust)", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="tli_robust", 
                        `title`="TLI (robust)", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rmsea_robust", 
                        `title`="RMSEA (robust)", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="verdict", 
                        `title`="Fit", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="fitNote",
                title="Model Fit \u2014 What It Means"))
            self$add(jmvcore::Table$new(
                options=options,
                name="solutionDiagnosticsTable",
                title="Solution Admissibility",
                rows=0,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="converged", 
                        `title`="Converged", 
                        `type`="text"),
                    list(
                        `name`="admissible", 
                        `title`="Admissible", 
                        `type`="text"),
                    list(
                        `name`="negVariances", 
                        `title`="Negative Residual Variances", 
                        `type`="integer"),
                    list(
                        `name`="loadingsOutOfBounds", 
                        `title`="Loadings \u2265 1", 
                        `type`="integer"),
                    list(
                        `name`="maxLatentCorr", 
                        `title`="Max. Latent Correlation", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="emptyCellPairs", 
                        `title`="Item Pairs with Empty Cells", 
                        `type`="integer"),
                    list(
                        `name`="nAnalyzed", 
                        `title`="n Analyzed", 
                        `type`="integer"),
                    list(
                        `name`="nAvailable", 
                        `title`="n Available", 
                        `type`="integer"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="solutionDiagnosticsNote",
                title="Solution Admissibility \u2014 What It Means"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modelComparisonTable",
                title="Model Comparison: Second-Order vs. Correlated Factors (Likelihood-Ratio Test)",
                visible="(secondOrder)",
                rows=0,
                columns=list(
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="dchisq", 
                        `title`="\u0394\u03C7\u00B2", 
                        `type`="number", 
                        `format`="zto,digits=2"),
                    list(
                        `name`="ddf", 
                        `title`="\u0394df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="verdict", 
                        `title`="Verdict", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="modelComparisonNote",
                title="Model Comparison \u2014 What It Means",
                visible="(secondOrder)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotFitComparison",
                title="Model Fit Comparison",
                width=500,
                height=350,
                renderFun=".plotFitComparison",
                visible="(showPlots && secondOrder)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotFitComparisonNote",
                title="Model Fit Comparison \u2014 What It Means",
                visible="(showPlots && secondOrder)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="reliabilityTable",
                title="Reliability by Factor",
                rows=0,
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="items", 
                        `title`="Items", 
                        `type`="integer"),
                    list(
                        `name`="cr", 
                        `title`="CR / \u03C9", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ave", 
                        `title`="AVE", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="h", 
                        `title`="H", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rel_g", 
                        `title`="Reliability due to G", 
                        `type`="number", 
                        `format`="zto,digits=3", 
                        `visible`="(secondOrder)"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="reliabilityNote",
                title="Reliability by Factor \u2014 What It Means"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotComparison",
                title="Reliability Comparison",
                width=600,
                height=350,
                renderFun=".plotComparison",
                visible="(showPlots)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotComparisonNote",
                title="Reliability Comparison \u2014 What It Means",
                visible="(showPlots)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotLoadings",
                title="Standardized Loadings by Factor",
                width=700,
                height=450,
                renderFun=".plotLoadings",
                visible="(showPlots)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotLoadingsNote",
                title="Standardized Loadings \u2014 What It Means",
                visible="(showPlots)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="htmtTable",
                title="Discriminant Validity (HTMT)",
                rows=0,
                columns=list(
                    list(
                        `name`="factor_a", 
                        `title`="Factor A", 
                        `type`="text"),
                    list(
                        `name`="factor_b", 
                        `title`="Factor B", 
                        `type`="text"),
                    list(
                        `name`="htmt", 
                        `title`="HTMT", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="verdict", 
                        `title`="Verdict", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="htmtNote",
                title="Discriminant Validity \u2014 What It Means"))
            self$add(jmvcore::Html$new(
                options=options,
                name="omegaHNote",
                title="Second-Order Omega Hierarchical",
                visible="(secondOrder)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="modificationIndicesTable",
                title="Modification Indices (interpret through theory, not automatically)",
                rows=0,
                columns=list(
                    list(
                        `name`="suggestion", 
                        `title`="Suggested parameter", 
                        `type`="text"),
                    list(
                        `name`="type", 
                        `title`="Type", 
                        `type`="text"),
                    list(
                        `name`="mi", 
                        `title`="MI", 
                        `type`="number", 
                        `format`="zto,digits=2"),
                    list(
                        `name`="epc", 
                        `title`="Expected Change", 
                        `type`="number", 
                        `format`="zto,digits=3"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="modificationIndicesNote",
                title="Modification Indices \u2014 What It Means"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Interpretation & Recommendations"))}))

advancedReliabilityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "advancedReliabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "advancedReliability",
                version = c(1,0,0),
                options = options,
                results = advancedReliabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Advanced Reliability (SEM)
#'
#' 
#' @param data .
#' @param secondOrder .
#' @param itemType .
#' @param estimator .
#' @param missingData .
#' @param factors .
#' @param showPlots .
#' @param plotStyle .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$fitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$fitNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$solutionDiagnosticsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$solutionDiagnosticsNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modelComparisonTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modelComparisonNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotFitComparison} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotFitComparisonNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$reliabilityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reliabilityNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotComparison} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotComparisonNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotLoadings} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotLoadingsNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$htmtTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$htmtNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$omegaHNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$modificationIndicesTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$modificationIndicesNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fitTable$asDF}
#'
#' \code{as.data.frame(results$fitTable)}
#'
#' @export
advancedReliability <- function(
    data,
    secondOrder = FALSE,
    itemType = "auto",
    estimator = "auto",
    missingData = "listwise",
    factors = list(
                list(label="Factor 1", vars=list())),
    showPlots = TRUE,
    plotStyle = "gray",
    reportLang = "en") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("advancedReliability requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- advancedReliabilityOptions$new(
        secondOrder = secondOrder,
        itemType = itemType,
        estimator = estimator,
        missingData = missingData,
        factors = factors,
        showPlots = showPlots,
        plotStyle = plotStyle,
        reportLang = reportLang)

    analysis <- advancedReliabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

