
# This file is automatically generated, you probably don't want to edit this

bibliographyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bibliographyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            topic = NULL,
            citationStyle = NULL,
            reportLang = NULL, ...) {

            super$initialize(
                package="fiabilitylab",
                name="bibliography",
                requiresData=FALSE,
                ...)

            private$..topic <- jmvcore::OptionList$new(
                "topic",
                topic,
                options=list(
                    "all",
                    "ctt",
                    "irr",
                    "gtheory",
                    "irt"))
            private$..citationStyle <- jmvcore::OptionList$new(
                "citationStyle",
                citationStyle,
                options=list(
                    "apa",
                    "vancouver",
                    "ieee"))
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"))

            self$.addOption(private$..topic)
            self$.addOption(private$..citationStyle)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        topic = function() private$..topic$value,
        citationStyle = function() private$..citationStyle$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..topic = NA,
        ..citationStyle = NA,
        ..reportLang = NA)
)

bibliographyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bibliographyResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        references = function() private$.items[["references"]],
        notes = function() private$.items[["notes"]],
        citationsTable = function() private$.items[["citationsTable"]],
        biblioSummary = function() private$.items[["biblioSummary"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bibliography")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Bibliography"))
            self$add(jmvcore::Html$new(
                options=options,
                name="references",
                title="References"))
            self$add(jmvcore::Html$new(
                options=options,
                name="notes",
                title="Curation Notes"))
            self$add(jmvcore::Html$new(
                options=options,
                name="citationsTable",
                title="Citations"))
            self$add(jmvcore::Html$new(
                options=options,
                name="biblioSummary",
                title="Bibliometric Summary"))}))

bibliographyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "bibliographyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "bibliography",
                version = c(1,0,0),
                options = options,
                results = bibliographyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Bibliography
#'
#' 
#' @param topic .
#' @param citationStyle .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$references} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$citationsTable} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$biblioSummary} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
bibliography <- function(
    topic,
    citationStyle,
    reportLang) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("bibliography requires jmvcore to be installed (restart may be required)")


    options <- bibliographyOptions$new(
        topic = topic,
        citationStyle = citationStyle,
        reportLang = reportLang)

    analysis <- bibliographyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

