
# This file is automatically generated, you probably don't want to edit this

fiabilityLibraryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fiabilityLibraryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            category = NULL,
            detail = NULL,
            reportLang = NULL, ...) {

            super$initialize(
                package="fiabilitylab",
                name="fiabilityLibrary",
                requiresData=FALSE,
                ...)

            private$..category <- jmvcore::OptionList$new(
                "category",
                category,
                options=list(
                    "concepts",
                    "theories",
                    "errors"))
            private$..detail <- jmvcore::OptionList$new(
                "detail",
                detail,
                options=list(
                    "summary",
                    "full"))
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"))

            self$.addOption(private$..category)
            self$.addOption(private$..detail)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        category = function() private$..category$value,
        detail = function() private$..detail$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..category = NA,
        ..detail = NA,
        ..reportLang = NA)
)

fiabilityLibraryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fiabilityLibraryResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fiability Library")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))}))

fiabilityLibraryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fiabilityLibraryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "fiabilityLibrary",
                version = c(1,0,0),
                options = options,
                results = fiabilityLibraryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Fiability Library
#'
#' 
#' @param category .
#' @param detail .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
fiabilityLibrary <- function(
    category,
    detail,
    reportLang) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("fiabilityLibrary requires jmvcore to be installed (restart may be required)")


    options <- fiabilityLibraryOptions$new(
        category = category,
        detail = detail,
        reportLang = reportLang)

    analysis <- fiabilityLibraryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

