
# This file is automatically generated, you probably don't want to edit this

fiabilityLibraryOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fiabilityLibraryOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            category = "all", ...) {

            super$initialize(
                package="fiabilitylab",
                name="fiabilityLibrary",
                requiresData=FALSE,
                ...)

            private$..category <- jmvcore::OptionList$new(
                "category",
                category,
                options=list(
                    "all",
                    "internalConsistency",
                    "interRater",
                    "advanced",
                    "invariance",
                    "foundations",
                    "errors"),
                default="all")

            self$.addOption(private$..category)
        }),
    active = list(
        category = function() private$..category$value),
    private = list(
        ..category = NA)
)

fiabilityLibraryResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fiabilityLibraryResults",
    inherit = jmvcore::Group,
    active = list(
        intro = function() private$.items[["intro"]],
        internalConsistency = function() private$.items[["internalConsistency"]],
        interRater = function() private$.items[["interRater"]],
        advanced = function() private$.items[["advanced"]],
        invariance = function() private$.items[["invariance"]],
        foundations = function() private$.items[["foundations"]],
        errors = function() private$.items[["errors"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fiability Library")
            self$add(jmvcore::Html$new(
                options=options,
                name="intro",
                title="Introduction"))
            self$add(jmvcore::Html$new(
                options=options,
                name="internalConsistency",
                title="Internal Consistency"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interRater",
                title="Inter-Rater Agreement"))
            self$add(jmvcore::Html$new(
                options=options,
                name="advanced",
                title="Advanced Reliability (SEM)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="invariance",
                title="Measurement Invariance"))
            self$add(jmvcore::Html$new(
                options=options,
                name="foundations",
                title="Theoretical Foundations"))
            self$add(jmvcore::Html$new(
                options=options,
                name="errors",
                title="Common Errors"))}))

fiabilityLibraryBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fiabilityLibraryBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "fiabilityLibrary",
                version = c(1,5,0),
                options = options,
                results = fiabilityLibraryResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Fiability Library
#'
#' 
#' @param category .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$intro} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$internalConsistency} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interRater} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$advanced} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$invariance} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$foundations} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$errors} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
fiabilityLibrary <- function(
    category = "all") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("fiabilityLibrary requires jmvcore to be installed (restart may be required)")


    options <- fiabilityLibraryOptions$new(
        category = category)

    analysis <- fiabilityLibraryClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

