# -----------------------------------------------------------------------------------
# FiabilityLab
# A Jamovi module for reliability and inter-rater agreement analysis and
# methodological decision support.
#
# Copyright (C) 2026 Arquímedes De León Chacón Chacón
#
# This file is part of FiabilityLab.
#
# FiabilityLab is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# FiabilityLab is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FiabilityLab.
# If not, see https://www.gnu.org/licenses/.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# FiabilityLab - Fiability Library.
#
# A reference glossary explaining what each reliability coefficient and
# theoretical framework means and when it applies, across FiabilityLab. It
# does not analyze the user's data; each analysis module interprets its own
# results separately. Every claim that names a specific method is anchored to
# its source citation (Author, Year), matching every entry already curated in
# the Bibliography module -- no coefficient appears here without a citation,
# and no citation appears here without a matching Bibliography entry.
#
# ES: Un glosario de referencia que explica qué significa cada coeficiente de
# confiabilidad y marco teórico, y cuándo aplica, en todo FiabilityLab. No
# analiza los datos del usuario; cada módulo de análisis interpreta sus
# propios resultados por separado. Toda afirmación que nombra un método
# específico está anclada a su cita de origen (Autor, Año), coincidiendo con
# cada entrada ya curada en el módulo Bibliography -- ningún coeficiente
# aparece aquí sin una cita, y ninguna cita aparece aquí sin una entrada
# correspondiente en Bibliography.
# -----------------------------------------------------------------------------

fiabilityLibraryClass <- if (requireNamespace("jmvcore", quietly = TRUE)) R6::R6Class(
  "fiabilityLibraryClass",
  inherit = fiabilityLibraryBase,
  private = list(

    # Report-text translation dispatch -- see shared-helpers.R's own
    # note on .fl_tr() for why this stays separate from jamovi's native
    # .() catalog (which still drives every YAML-derived title/label).
    .tr = function(en, es) .fl_tr(en, es, self$options$reportLang),

    .esc = function(x) {
      x <- gsub("&", "&amp;", x, fixed = TRUE)
      x <- gsub("<", "&lt;", x, fixed = TRUE)
      x <- gsub(">", "&gt;", x, fixed = TRUE)
      x
    },

    .title_html = function(title) {
      paste0('<p style="font-weight:700;font-size:1.1em;line-height:1;margin:0 0 0.5em 0;">', title, '</p>')
    },

    .table_html = function(headers, rows) {
      th <- paste0('<th style="text-align:left;padding:4px 8px;border-bottom:2px solid #999;font-weight:700;">',
                   headers, '</th>', collapse = "")
      trs <- vapply(rows, function(r) {
        tds <- paste0('<td style="text-align:left;padding:4px 8px;border-bottom:1px solid #ddd;vertical-align:top;">',
                      r, '</td>', collapse = "")
        paste0("<tr>", tds, "</tr>")
      }, character(1))
      paste0('<table style="border-collapse:collapse;width:100%;margin:0.5em 0 0.8em 0;font-size:0.92em;line-height:1;">',
             "<thead><tr>", th, "</tr></thead><tbody>", paste(trs, collapse = ""), "</tbody></table>")
    },

    # EN: text-align: justify here (and line-height: 1 on every element
    # below) is the same convention Bibliography uses for its own body
    # text -- see .fl_prose_open() in shared-helpers.R, used by
    # internalConsistency and interRater's Html panels for the same reason.
    # ES: text-align: justify aquí (y line-height: 1 en cada elemento de
    # abajo) es la misma convención que usa Bibliography para su propio
    # texto corrido -- ver .fl_prose_open() en shared-helpers.R, usado por
    # los paneles Html de internalConsistency e interRater por el mismo motivo.
    .section = function(title, body_html) {
      paste0('<div style="max-width:7.25in;width:100%;box-sizing:border-box;line-height:1;text-align:justify;">',
             private$.title_html(title), body_html, '</div>')
    },

    .p = function(...) paste0('<p style="margin:0 0 0.7em 0;line-height:1;">', paste0(...), '</p>'),

    .h4 = function(x) paste0('<p style="margin:0.9em 0 0.2em 0;font-weight:700;line-height:1;">', x, '</p>'),

    .run = function() {
      category <- self$options$category

      esc   <- private$.esc
      tbl   <- private$.table_html
      sect  <- private$.section
      p     <- private$.p
      h4    <- private$.h4

      # ── Intro (always shown) ──────────────────────────────────────────────
      intro_html <- sect(
        private$.tr("Fiability Library", "Biblioteca de Confiabilidad"),
        paste0(
          p(private$.tr("Welcome to FiabilityLab. <b>Reliability</b> is the consistency of a measure: an instrument is reliable if it produces similar results under consistent conditions. FiabilityLab covers three main designs \u2014 <b>internal consistency</b> (one instrument, one administration), <b>inter-rater agreement</b> (multiple raters, one occasion), and <b>temporal stability</b> (one instrument, repeated occasions; planned).", "Bienvenido a FiabilityLab. La <b>confiabilidad</b> es la consistencia de una medida: un instrumento es confiable si produce resultados similares bajo condiciones consistentes. FiabilityLab cubre tres dise\u00F1os principales \u2014 <b>consistencia interna</b> (un instrumento, una administraci\u00F3n), <b>acuerdo entre jueces</b> (varios jueces, una ocasi\u00F3n), y <b>estabilidad temporal</b> (un instrumento, ocasiones repetidas; planificado).")),
          p(private$.tr("Every coefficient below is anchored to the source that introduced or formalized it. Full bibliographic details for every citation live in the Bibliography module.", "Cada coeficiente de abajo est\u00E1 anclado a la fuente que lo introdujo o formaliz\u00F3. Los detalles bibliogr\u00E1ficos completos de cada cita est\u00E1n en el m\u00F3dulo Bibliography."))
        )
      )

      # ── Internal Consistency ───────────────────────────────────────────────
      ic_table <- tbl(
        c(private$.tr("Coefficient", "Coeficiente"), private$.tr("What it estimates", "Qu\u00E9 estima"),
          private$.tr("Typical use", "Uso t\u00EDpico"), private$.tr("Main limitation", "Limitaci\u00F3n principal")),
        list(
          c("Cronbach's α",
            private$.tr("Reliability assuming &tau;-equivalence (equal item loadings)", "Confiabilidad asumiendo &tau;-equivalencia (cargas de \u00EDtem iguales)"),
            private$.tr("Likert/continuous items; quick default estimate", "\u00CDtems Likert/continuos; estimaci\u00F3n por defecto r\u00E1pida"),
            private$.tr("Biased (usually deflated) when loadings are unequal or the scale is multidimensional (Cronbach, 1951)", "Sesgada (usualmente subestimada) cuando las cargas son desiguales o la escala es multidimensional (Cronbach, 1951)")),
          c(private$.tr("Ordinal \u03B1", "Alfa Ordinal"),
            private$.tr("Same standardized-\u03B1 formula, computed on polychoric correlations", "Misma f\u00F3rmula de \u03B1 estandarizado, calculada sobre correlaciones polic\u00F3ricas"),
            private$.tr("Ordinal/Likert items with few categories or skewed distributions", "\u00CDtems ordinales/Likert con pocas categor\u00EDas o distribuciones sesgadas"),
            private$.tr("Not interchangeable with raw \u03B1; can differ by .05\u2013.10+ on skewed data (Zumbo et al., 2007)", "No es intercambiable con el \u03B1 bruto; puede diferir en .05\u2013.10+ en datos sesgados (Zumbo et al., 2007)")),
          c(private$.tr("McDonald's \u03C9 (total)", "Omega de McDonald (\u03C9 total)"),
            private$.tr("Reliability from actual factor loadings; no equal-loading assumption", "Confiabilidad a partir de cargas factoriales reales; sin supuesto de cargas iguales"),
            private$.tr("General-purpose default; robust to unequal loadings", "Estimaci\u00F3n por defecto de uso general; robusta a cargas desiguales"),
            private$.tr("Requires a fitted factor model (McDonald, 1999)", "Requiere un modelo factorial ajustado (McDonald, 1999)")),
          c(private$.tr("McDonald's \u03C9 hierarchical (\u03C9\u2095)", "\u03C9 Jer\u00E1rquico de McDonald (\u03C9\u2095)"),
            private$.tr("Variance due to one general factor, net of group-factor variance", "Varianza debida a un factor general, descontando la varianza de factores de grupo"),
            private$.tr("Multidimensional/bifactor scales", "Escalas multidimensionales/bifactor"),
            private$.tr("Meaningless with only 1 factor fit \u2014 collapses onto \u03C9 total (McDonald, 1999)", "Sin sentido con un ajuste de un solo factor \u2014 colapsa sobre el \u03C9 total (McDonald, 1999)")),
          c("GLB",
            private$.tr("Tightest model-free lower bound on reliability", "Cota inferior libre de modelo m\u00E1s ajustada de confiabilidad"),
            private$.tr("Sensitivity check against \u03B1/\u03C9, no distributional assumptions", "Verificaci\u00F3n de sensibilidad frente a \u03B1/\u03C9, sin supuestos distribucionales"),
            private$.tr("Upward-biased in small samples relative to item count", "Sesgado al alza en muestras peque\u00F1as en relaci\u00F3n con el n\u00FAmero de \u00EDtems")),
          c(private$.tr("Split-half (Spearman-Brown)", "Mitades partidas (Spearman-Brown)"),
            private$.tr("Full-test reliability estimated from two-half correlation", "Confiabilidad de la prueba completa estimada de la correlaci\u00F3n entre dos mitades"),
            private$.tr("Quick cross-check for long instruments", "Verificaci\u00F3n r\u00E1pida para instrumentos largos"),
            private$.tr("Highly sensitive to which items land in which half", "Muy sensible a qu\u00E9 \u00EDtems caen en cada mitad")),
          c("Guttman λ2 / λ6",
            private$.tr("Model-free lower bounds (alternative to GLB)", "Cotas inferiores libres de modelo (alternativa al GLB)"),
            private$.tr("Tighter lower bound without fitting a factor model", "Cota inferior m\u00E1s ajustada sin ajustar un modelo factorial"),
            private$.tr("\u03BB6 unstable with near-duplicate items", "\u03BB6 inestable con \u00EDtems casi duplicados")),
          c("KR-20 / KR-21",
            private$.tr("\u03B1 specialized to dichotomous (0/1) items", "\u03B1 especializado a \u00EDtems dicot\u00F3micos (0/1)"),
            private$.tr("Knowledge/aptitude tests scored right/wrong", "Pruebas de conocimiento/aptitud calificadas correcto/incorrecto"),
            private$.tr("KR-21 assumes equal item difficulty \u2014 understates reliability when difficulties vary (Kuder &amp; Richardson, 1937)", "El KR-21 asume igual dificultad de \u00EDtem \u2014 subestima la confiabilidad cuando las dificultades var\u00EDan (Kuder &amp; Richardson, 1937)"))
        )
      )

      ic_body <- paste0(
        p(private$.tr("<b>What it assesses:</b> Internal consistency evaluates whether the items of a single instrument, administered once, measure the same underlying construct. Under Classical Test Theory, an observed score X = T + E (true score plus error), and reliability is the proportion of observed variance attributable to T (Cronbach, 1951; McDonald, 1999; Nunnally &amp; Bernstein, 1994).", "<b>Qu\u00E9 eval\u00FAa:</b> La consistencia interna eval\u00FAa si los \u00EDtems de un instrumento, administrado una vez, miden el mismo constructo subyacente. Bajo la Teor\u00EDa Cl\u00E1sica de los Tests, una puntuaci\u00F3n observada X = T + E (puntuaci\u00F3n verdadera m\u00E1s error), y la confiabilidad es la proporci\u00F3n de varianza observada atribuible a T (Cronbach, 1951; McDonald, 1999; Nunnally &amp; Bernstein, 1994).")),
        p(private$.tr("<b>Where it's used in FiabilityLab:</b> the Internal Consistency module computes every coefficient in the table below.", "<b>D\u00F3nde se usa en FiabilityLab:</b> el m\u00F3dulo Internal Consistency calcula cada coeficiente de la tabla de abajo.")),
        p(private$.tr("<b>How the module's discordance panel is interpreted:</b> McDonald's \u03C9 is treated as the general-purpose reference coefficient, since it uses the model's actual factor loadings instead of assuming they are equal; Cronbach's \u03B1 is reported alongside it, and when the two diverge by more than a small margin, \u03C9 is trusted over \u03B1 \u2014 a large gap signals broken &tau;-equivalence. Ordinal \u03B1 is preferred over raw \u03B1 when items are ordinal or markedly non-normal (Zumbo et al., 2007). GLB and the Guttman \u03BBs serve as model-free sensitivity checks. KR-20/KR-21 apply only to strictly dichotomous items (Kuder &amp; Richardson, 1937).", "<b>C\u00F3mo se interpreta el panel de discordancia del m\u00F3dulo:</b> el \u03C9 de McDonald se trata como el coeficiente de referencia de uso general, ya que usa las cargas factoriales reales del modelo en vez de asumir que son iguales; el \u03B1 de Cronbach se reporta junto a \u00E9l, y cuando ambos divergen m\u00E1s de un margen peque\u00F1o, se conf\u00EDa en el \u03C9 sobre el \u03B1 \u2014 una brecha grande se\u00F1ala una ruptura de la &tau;-equivalencia. El \u03B1 Ordinal se prefiere sobre el \u03B1 bruto cuando los \u00EDtems son ordinales o marcadamente no normales (Zumbo et al., 2007). El GLB y los \u03BB de Guttman sirven como verificaciones de sensibilidad libres de modelo. El KR-20/KR-21 aplican solo a \u00EDtems estrictamente dicot\u00F3micos (Kuder &amp; Richardson, 1937).")),
        ic_table,
        h4(private$.tr("Cronbach's \u03B1", "Alfa de Cronbach (\u03B1)")),
        p(private$.tr("The average of all possible split-half reliabilities; equivalently, the proportion of total-score variance attributable to a common source among items, under the assumption that every item contributes equally to the true score (Cronbach, 1951).", "El promedio de todas las confiabilidades posibles de mitades partidas; equivalentemente, la proporci\u00F3n de la varianza del puntaje total atribuible a una fuente com\u00FAn entre \u00EDtems, bajo el supuesto de que cada \u00EDtem contribuye igualmente a la puntuaci\u00F3n verdadera (Cronbach, 1951).")),
        h4(private$.tr("\u03B1's Assumptions Check", "Verificaci\u00F3n de Supuestos del \u03B1")),
        p(private$.tr("\u03B1 equals the true reliability only when items are tau-equivalent \u2014 equal true-score loadings on a single common factor (Cronbach, 1951; Zumbo, Gadermann &amp; Zeisser, 2007). Unlike McDonald's \u03C9, GLB, or the Guttman \u03BB family (none of which require this), \u03B1 is biased \u2014 usually downward \u2014 whenever tau-equivalence fails. FiabilityLab's Internal Consistency module tests this formally as a likelihood-ratio comparison between a congeneric single-factor CFA (item loadings free) and a tau-equivalent one (loadings constrained equal): a significant difference rejects tau-equivalence, in which case \u03C9 should be reported instead of \u03B1. This requires the lavaan package; when it is unavailable, the discordance panel's \u03B1-vs-\u03C9 gap remains as an indirect signal of the same thing.", "El \u03B1 equivale a la confiabilidad verdadera solo cuando los \u00EDtems son tau-equivalentes \u2014 iguales cargas de puntaje verdadero sobre un \u00FAnico factor com\u00FAn (Cronbach, 1951; Zumbo, Gadermann &amp; Zeisser, 2007). A diferencia del \u03C9 de McDonald, el GLB o la familia \u03BB de Guttman (ninguno de los cuales lo requiere), el \u03B1 est\u00E1 sesgado \u2014 usualmente a la baja \u2014 cuando la tau-equivalencia falla. El m\u00F3dulo Internal Consistency de FiabilityLab prueba esto formalmente como una comparaci\u00F3n de raz\u00F3n de verosimilitud entre un AFC congen\u00E9rico de un factor (cargas de \u00EDtem libres) y uno tau-equivalente (cargas restringidas a ser iguales): una diferencia significativa rechaza la tau-equivalencia, en cuyo caso debe reportarse el \u03C9 en vez del \u03B1. Esto requiere el paquete lavaan; cuando no est\u00E1 disponible, la brecha \u03B1-vs-\u03C9 del panel de discordancia sigue siendo una se\u00F1al indirecta de lo mismo.")),
        p(private$.tr("\u03B1's standard-error formula also assumes approximate multivariate normality and unidimensionality (a single common factor). FiabilityLab's assumptions check reuses the parallel-analysis factor count for the latter \u2014 so the same three checks (tau-equivalence, normality, unidimensionality) that determine whether \u03B1 is trustworthy are reported together in one panel, the way interRater reports ICC's normality/homoscedasticity/linearity checks together.", "La f\u00F3rmula del error est\u00E1ndar del \u03B1 tambi\u00E9n asume normalidad multivariada aproximada y unidimensionalidad (un solo factor com\u00FAn). La verificaci\u00F3n de supuestos de FiabilityLab reutiliza el conteo de factores del an\u00E1lisis paralelo para esto \u00FAltimo \u2014 as\u00ED los mismos tres supuestos (tau-equivalencia, normalidad, unidimensionalidad) que determinan si el \u03B1 es confiable se reportan juntos en un panel, de la misma forma en que interRater reporta juntos los supuestos de normalidad/homocedasticidad/linealidad del ICC.")),
        p(private$.tr("The normality check itself is measurement-level-aware rather than applying Shapiro-Wilk unconditionally: Shapiro-Wilk assumes a genuinely continuous variable, so running it on a discrete Likert item (a handful of whole-number categories) mostly detects the item's own discreteness/ties rather than a real distributional problem \u2014 a module whose purpose is checking assumptions should not itself apply a continuous-data test to ordinal data. FiabilityLab therefore runs Shapiro-Wilk only when items are genuinely continuous; for ordinal (Likert-type, \u22647 whole-number categories) items it instead flags items exceeding |skew| &gt; 2 or |kurtosis| &gt; 7, the same floor/ceiling-effect threshold already used elsewhere in this module; and it runs no normality check at all on dichotomous items, since the concept does not apply to a two-point (Bernoulli) variable.", "La propia verificaci\u00F3n de normalidad es consciente del nivel de medida en vez de aplicar Shapiro-Wilk sin condici\u00F3n: Shapiro-Wilk asume una variable genuinamente continua, as\u00ED que aplicarla a un \u00EDtem Likert discreto (un pu\u00F1ado de categor\u00EDas de n\u00FAmeros enteros) detecta mayormente la propia discreci\u00F3n/empates del \u00EDtem en vez de un problema distribucional real \u2014 un m\u00F3dulo cuyo prop\u00F3sito es verificar supuestos no deber\u00EDa \u00E9l mismo aplicar una prueba para datos continuos a datos ordinales. Por ello, FiabilityLab corre Shapiro-Wilk solo cuando los \u00EDtems son genuinamente continuos; para \u00EDtems ordinales (tipo Likert, \u22647 categor\u00EDas de n\u00FAmeros enteros) marca en cambio los \u00EDtems que exceden |asimetr\u00EDa| &gt; 2 o |curtosis| &gt; 7, el mismo umbral de efecto techo/piso ya usado en otras partes de este m\u00F3dulo; y no aplica ninguna verificaci\u00F3n de normalidad a \u00EDtems dicot\u00F3micos, ya que el concepto no aplica a una variable de dos puntos (Bernoulli).")),
        h4(private$.tr("Ordinal \u03B1 (polychoric)", "Alfa Ordinal (polic\u00F3rica)")),
        p(private$.tr("The same standardized-\u03B1 formula, applied to the polychoric correlation matrix \u2014 which models each ordinal item as a coarsely categorized continuous variable \u2014 instead of Pearson correlations (Zumbo, Gadermann &amp; Zeisser, 2007).", "La misma f\u00F3rmula del \u03B1 estandarizado, aplicada a la matriz de correlaci\u00F3n polic\u00F3rica \u2014 que modela cada \u00EDtem ordinal como una variable continua categorizada groseramente \u2014 en vez de correlaciones de Pearson (Zumbo, Gadermann &amp; Zeisser, 2007).")),
        h4(private$.tr("McDonald's \u03C9 (total and hierarchical)", "\u03C9 de McDonald (total y jer\u00E1rquico)")),
        p(private$.tr("\u03C9 total is the proportion of total-score variance explained by a fitted factor model, computed from the model's actual loadings rather than assuming they are equal (McDonald, 1999). \u03C9 hierarchical (\u03C9\u2095) is the narrower quantity: the variance attributable specifically to ONE general factor running through all items, net of whatever group-factor (subscale) variance also exists \u2014 it requires a genuine bifactor/multi-factor model, and is not a distinct number from \u03C9 total when only one factor is fit.", "El \u03C9 total es la proporci\u00F3n de varianza del puntaje total explicada por un modelo factorial ajustado, calculada a partir de las cargas reales del modelo en vez de asumir que son iguales (McDonald, 1999). El \u03C9 jer\u00E1rquico (\u03C9\u2095) es la cantidad m\u00E1s estrecha: la varianza atribuible espec\u00EDficamente a UN factor general que atraviesa todos los \u00EDtems, descontando la varianza de factores de grupo (subescalas) que tambi\u00E9n exista \u2014 requiere un modelo bifactor/multi-factor genuino, y no es un n\u00FAmero distinto del \u03C9 total cuando solo se ajusta un factor.")),
        h4("GLB (Greatest Lower Bound)"),
        p(private$.tr("The mathematically tightest lower-bound estimate of reliability achievable without any distributional or factor-structure assumption, obtained by constrained optimization over the item covariance matrix. Known to be upward-biased in small samples relative to the number of items.", "La estimaci\u00F3n de l\u00EDmite inferior matem\u00E1ticamente m\u00E1s ajustada de confiabilidad alcanzable sin ning\u00FAn supuesto distribucional o de estructura factorial, obtenida mediante optimizaci\u00F3n restringida sobre la matriz de covarianza de \u00EDtems. Se sabe que est\u00E1 sesgada al alza en muestras peque\u00F1as en relaci\u00F3n con el n\u00FAmero de \u00EDtems.")),
        h4(private$.tr("Split-half (Spearman-Brown)", "Mitades partidas (Spearman-Brown)")),
        p(private$.tr("Correlates two halves of the test, then corrects that correlation upward with the Spearman-Brown prophecy formula to estimate the reliability of the full-length test. Highly sensitive to which items land in which half, which is why FiabilityLab reports the mean across many random splits rather than a single one.", "Correlaciona dos mitades de la prueba, y luego corrige esa correlaci\u00F3n al alza con la f\u00F3rmula de profec\u00EDa de Spearman-Brown para estimar la confiabilidad de la prueba completa. Muy sensible a qu\u00E9 \u00EDtems caen en cada mitad, por lo que FiabilityLab reporta el promedio entre muchas particiones aleatorias en vez de una sola.")),
        h4(private$.tr("Guttman \u03BB2 / \u03BB6", "Guttman \u03BB2 / \u03BB6")),
        p(private$.tr("Model-free lower-bound estimates of reliability, like GLB but computed differently: \u03BB2 uses the covariance structure directly; \u03BB6 uses each item's squared multiple correlation with the rest of the scale. \u03BB6 becomes unstable when an item correlates almost perfectly with the rest of the scale.", "Estimaciones de l\u00EDmite inferior de confiabilidad libres de modelo, como el GLB pero calculadas de forma distinta: \u03BB2 usa directamente la estructura de covarianza; \u03BB6 usa la correlaci\u00F3n m\u00FAltiple al cuadrado de cada \u00EDtem con el resto de la escala. El \u03BB6 se vuelve inestable cuando un \u00EDtem correlaciona casi perfectamente con el resto de la escala.")),
        h4("KR-20 / KR-21 (Kuder-Richardson)"),
        p(private$.tr("KR-20 is Cronbach's \u03B1 specialized to strictly dichotomous (0/1) items, computed from each item's p&middot;q variance; KR-21 further simplifies KR-20 by assuming all items share the same difficulty (proportion correct) (Kuder &amp; Richardson, 1937). KR-21 understates reliability when item difficulties actually vary.", "El KR-20 es el \u03B1 de Cronbach especializado a \u00EDtems estrictamente dicot\u00F3micos (0/1), calculado a partir de la varianza p&middot;q de cada \u00EDtem; el KR-21 simplifica a\u00FAn m\u00E1s al KR-20 asumiendo que todos los \u00EDtems comparten la misma dificultad (proporci\u00F3n de aciertos) (Kuder &amp; Richardson, 1937). El KR-21 subestima la confiabilidad cuando las dificultades de los \u00EDtems en realidad var\u00EDan."))
      )
      internalConsistency_html <- sect(private$.tr("Internal Consistency", "Consistencia Interna"), ic_body)

      # ── Inter-Rater Agreement (ahead of interRater's code, per the ─────────
      # Library/Bibliography admission contract) ─────────────────────────────
      irr_table <- tbl(
        c(private$.tr("Coefficient", "Coeficiente"), private$.tr("Measurement level", "Nivel de medida"),
          private$.tr("Typical use", "Uso t\u00EDpico"), private$.tr("Main limitation", "Limitaci\u00F3n principal")),
        list(
          c(private$.tr("Cohen's Kappa", "Kappa de Cohen"), private$.tr("Nominal, 2 raters", "Nominal, 2 jueces"),
            private$.tr("Chance-corrected agreement, 2 raters, categorical", "Acuerdo corregido por azar, 2 jueces, categ\u00F3rico"),
            private$.tr("Paradoxically low with skewed category prevalence, even when raw agreement is high (Cohen, 1960; Gwet, 2014)", "Parad\u00F3jicamente bajo con prevalencia de categor\u00EDa sesgada, aun cuando el acuerdo bruto es alto (Cohen, 1960; Gwet, 2014)")),
          c(private$.tr("Fleiss' Kappa", "Kappa de Fleiss"), private$.tr("Nominal, &gt;2 raters", "Nominal, &gt;2 jueces"),
            private$.tr("Chance-corrected agreement, more than 2 raters", "Acuerdo corregido por azar, m\u00E1s de 2 jueces"),
            private$.tr("Same prevalence paradox as Cohen's Kappa", "La misma paradoja de prevalencia que el Kappa de Cohen")),
          c("Gwet's AC1 / AC2", private$.tr("Nominal/ordinal, any number of raters", "Nominal/ordinal, cualquier n\u00FAmero de jueces"),
            private$.tr("Robust alternative to Kappa under high/low prevalence", "Alternativa robusta al Kappa bajo prevalencia alta/baja"),
            private$.tr("Less familiar/standard in some fields (Gwet, 2014)", "Menos conocido/est\u00E1ndar en algunos campos (Gwet, 2014)")),
          c("ICC", private$.tr("Continuous/ordinal", "Continuo/ordinal"),
            private$.tr("Rater reliability for numeric scores; separates consistency from absolute agreement", "Confiabilidad entre jueces para puntajes num\u00E9ricos; separa consistencia de acuerdo absoluto"),
            private$.tr("Choosing the wrong of the 6 ICC forms changes the conclusion (Shrout &amp; Fleiss, 1979)", "Elegir la forma incorrecta entre las 6 de ICC cambia la conclusi\u00F3n (Shrout &amp; Fleiss, 1979)")),
          c(private$.tr("Krippendorff's \u03B1", "\u03B1 de Krippendorff"),
            private$.tr("Nominal/ordinal/interval/ratio, any raters, handles missing data", "Nominal/ordinal/intervalo/raz\u00F3n, cualquier n\u00FAmero de jueces, maneja datos faltantes"),
            private$.tr("Universal coefficient across measurement levels", "Coeficiente universal a trav\u00E9s de niveles de medida"),
            private$.tr("Less intuitive interpretation scale than Kappa (Krippendorff, 2018)", "Escala de interpretaci\u00F3n menos intuitiva que el Kappa (Krippendorff, 2018)")),
          c(private$.tr("Kendall's W", "W de Kendall"), private$.tr("Ordinal rankings", "Rankings ordinales"),
            private$.tr("Agreement among rankers on the ordering of objects", "Acuerdo entre evaluadores sobre el orden de los objetos"),
            private$.tr("Only applies to ranking data, not raw ratings", "Solo aplica a datos de ranking, no a calificaciones brutas"))
        )
      )

      irr_body <- paste0(
        p(private$.tr("<b>What it assesses:</b> Inter-rater agreement evaluates whether two or more independent raters/judges, scoring the same cases, reach consistent conclusions \u2014 at nominal, ordinal, or continuous measurement levels.", "<b>Qu\u00E9 eval\u00FAa:</b> El acuerdo entre jueces eval\u00FAa si dos o m\u00E1s jueces/evaluadores independientes, calificando los mismos casos, llegan a conclusiones consistentes \u2014 a nivel de medida nominal, ordinal o continuo.")),
        p(private$.tr("<b>Where it's used in FiabilityLab:</b> the Inter-Rater Agreement module (Kappa, Gwet's AC1/AC2, ICC, Krippendorff's \u03B1, Kendall's W).", "<b>D\u00F3nde se usa en FiabilityLab:</b> el m\u00F3dulo Inter-Rater Agreement (Kappa, AC1/AC2 de Gwet, ICC, \u03B1 de Krippendorff, W de Kendall).")),
        p(private$.tr("<b>How the module's discordance panel will be interpreted:</b> Cohen's/Fleiss' Kappa is compared against Gwet's AC1 \u2014 a large gap between them flags the \u201Ckappa paradox\u201D produced by skewed category prevalence, not genuinely poor agreement (Gwet, 2014).", "<b>C\u00F3mo se interpretar\u00E1 el panel de discordancia del m\u00F3dulo:</b> el Kappa de Cohen/Fleiss se compara frente al AC1 de Gwet \u2014 una brecha grande entre ambos se\u00F1ala la \u201Cparadoja del kappa\u201D producida por prevalencia de categor\u00EDa sesgada, no un acuerdo genuinamente pobre (Gwet, 2014).")),
        irr_table,
        h4(private$.tr("Cohen's / Fleiss' Kappa", "Kappa de Cohen / Fleiss")),
        p(private$.tr("Chance-corrected agreement for categorical (nominal) ratings: Cohen's Kappa for exactly 2 raters (Cohen, 1960), Fleiss' Kappa for more than 2 (Fleiss, 1971). Both can be paradoxically low even when raw agreement is high, whenever one category is much more common than the others \u2014 the \u201Ckappa paradox\u201D (Gwet, 2014). FiabilityLab reports Kappa values against the Landis &amp; Koch (1977) interpretation bands (Poor/Slight/Fair/Moderate/Substantial/Almost perfect), the field-standard scale for this coefficient.", "Acuerdo corregido por azar para calificaciones categ\u00F3ricas (nominales): el Kappa de Cohen para exactamente 2 jueces (Cohen, 1960), el Kappa de Fleiss para m\u00E1s de 2 (Fleiss, 1971). Ambos pueden ser parad\u00F3jicamente bajos aun con acuerdo bruto alto, cuando una categor\u00EDa es mucho m\u00E1s com\u00FAn que las dem\u00E1s \u2014 la \u201Cparadoja del kappa\u201D (Gwet, 2014). FiabilityLab reporta los valores de Kappa frente a las bandas de interpretaci\u00F3n de Landis &amp; Koch (1977) (Pobre/Leve/Aceptable/Moderado/Sustancial/Casi perfecto), la escala est\u00E1ndar del campo para este coeficiente.")),
        h4("Gwet's AC1 / AC2"),
        p(private$.tr("Proposed as a more stable alternative to Kappa specifically because it does not degrade under extreme category prevalence or rater bias (Gwet, 2014). AC1 is for nominal data, AC2 extends the same logic to ordinal/interval scales.", "Propuesto como una alternativa m\u00E1s estable al Kappa espec\u00EDficamente porque no se degrada ante prevalencia de categor\u00EDa extrema o sesgo del juez (Gwet, 2014). El AC1 es para datos nominales, el AC2 extiende la misma l\u00F3gica a escalas ordinales/de intervalo.")),
        h4("ICC (Intraclass Correlation)"),
        p(private$.tr("For continuous or ordinal ratings. There are six standard forms, differing in whether raters are treated as a fixed or random sample, whether reliability is for a single rating or an average of several, and \u2014 the choice with the biggest practical consequence \u2014 whether it measures pure consistency (rank agreement) or absolute agreement (identical values) (Shrout &amp; Fleiss, 1979). A rater with a systematic mean bias can score high on consistency-type ICC and low on absolute-agreement-type ICC for the exact same data.", "Para calificaciones continuas u ordinales. Existen seis formas est\u00E1ndar, que difieren en si los jueces se tratan como una muestra fija o aleatoria, si la confiabilidad es para una calificaci\u00F3n \u00FAnica o un promedio de varias, y \u2014 la elecci\u00F3n con mayor consecuencia pr\u00E1ctica \u2014 si mide consistencia pura (acuerdo de orden) o acuerdo absoluto (valores id\u00E9nticos) (Shrout &amp; Fleiss, 1979). Un juez con un sesgo sistem\u00E1tico de media puede puntuar alto en el ICC tipo consistencia y bajo en el tipo acuerdo absoluto para los mismos datos exactos.")),
        h4(private$.tr("ICC's Assumptions", "Supuestos del ICC")),
        p(private$.tr("Because the ICC is a variance-partition of a subject \u00D7 rater ANOVA (Shrout &amp; Fleiss, 1979), it \u2014 unlike Kappa, Gwet's AC1/AC2, Krippendorff's \u03B1, or Kendall's W, all of which are rank- or category-based and distribution-free \u2014 inherits that model's usual assumptions: normally-distributed residuals, homogeneous error variance across raters (homoscedasticity), and an additive/linear subject \u00D7 rater structure. FiabilityLab's Inter-Rater Agreement module tests all three automatically whenever ICC is computed: Shapiro-Wilk for normality, Levene's test (Levene, 1960) for homoscedasticity, and Tukey's one-degree-of-freedom test for non-additivity (Tukey, 1949) for linearity \u2014 the last of these is the most consequential violation, since a curvilinear rater relationship makes the ICC systematically understate true agreement.", "Como el ICC es una partici\u00F3n de varianza de un ANOVA sujeto \u00D7 juez (Shrout &amp; Fleiss, 1979), a diferencia del Kappa, el AC1/AC2 de Gwet, el \u03B1 de Krippendorff o la W de Kendall \u2014 todos de rango o categor\u00EDa y libres de distribuci\u00F3n \u2014 hereda los supuestos usuales de ese modelo: residuos normalmente distribuidos, varianza de error homog\u00E9nea entre jueces (homocedasticidad), y una estructura sujeto \u00D7 juez aditiva/lineal. El m\u00F3dulo Inter-Rater Agreement de FiabilityLab prueba los tres autom\u00E1ticamente siempre que se calcula el ICC: Shapiro-Wilk para normalidad, la prueba de Levene (Levene, 1960) para homocedasticidad, y la prueba de un grado de libertad de Tukey para no aditividad (Tukey, 1949) para linealidad \u2014 esta \u00FAltima es la violaci\u00F3n m\u00E1s consecuente, ya que una relaci\u00F3n curvil\u00EDnea entre jueces hace que el ICC subestime sistem\u00E1ticamente el acuerdo real.")),
        p(private$.tr("Sample size compounds all three: small samples (roughly n &lt; 30) both widen the ICC's confidence interval and make its F-based inference more sensitive to non-normality, while the coefficient's other assumptions (homoscedasticity, linearity) are unaffected by n but become harder to detect statistically with few subjects. FiabilityLab reports minimum-sample guidance from Koo &amp; Li (2016) and Bujang &amp; Baharum (2017) alongside the assumption tests. The bootstrap confidence intervals available for Kappa, Gwet, Krippendorff, and Kendall's W above are themselves the practical antidote to small-n imprecision for those coefficients, since none of them relies on ICC's F-distribution assumption in the first place.", "El tama\u00F1o de muestra agrava los tres supuestos: muestras peque\u00F1as (aproximadamente n &lt; 30) tanto ampl\u00EDan el intervalo de confianza del ICC como hacen su inferencia basada en F m\u00E1s sensible a la no normalidad, mientras que los otros supuestos del coeficiente (homocedasticidad, linealidad) no dependen de n pero son m\u00E1s dif\u00EDciles de detectar estad\u00EDsticamente con pocos sujetos. FiabilityLab reporta orientaci\u00F3n de tama\u00F1o m\u00EDnimo de muestra de Koo &amp; Li (2016) y Bujang &amp; Baharum (2017) junto a las pruebas de supuestos. Los intervalos de confianza por bootstrap disponibles para Kappa, Gwet, Krippendorff y la W de Kendall arriba son en s\u00ED mismos el ant\u00EDdoto pr\u00E1ctico ante la imprecisi\u00F3n por n peque\u00F1o para esos coeficientes, ya que ninguno depende del supuesto de distribuci\u00F3n F del ICC.")),
        h4(private$.tr("Krippendorff's \u03B1", "\u03B1 de Krippendorff")),
        p(private$.tr("A single, unified agreement coefficient that works across nominal, ordinal, interval, and ratio data, with any number of raters, and handles missing data natively (Krippendorff, 2018) \u2014 useful when a design mixes measurement levels or has incomplete rater coverage.", "Un coeficiente de acuerdo \u00FAnico y unificado que funciona con datos nominales, ordinales, de intervalo y de raz\u00F3n, con cualquier n\u00FAmero de jueces, y maneja datos faltantes de forma nativa (Krippendorff, 2018) \u2014 \u00FAtil cuando un dise\u00F1o mezcla niveles de medida o tiene cobertura incompleta de jueces.")),
        h4(private$.tr("Kendall's W", "W de Kendall")),
        p(private$.tr("Measures agreement among multiple rankers on the relative ORDER of a set of objects, not on their raw ratings \u2014 applicable only when the data are genuinely rankings.", "Mide el acuerdo entre varios evaluadores sobre el ORDEN relativo de un conjunto de objetos, no sobre sus calificaciones brutas \u2014 aplicable solo cuando los datos son genuinamente rankings."))
      )
      interRater_html <- sect(private$.tr("Inter-Rater Agreement", "Acuerdo entre Jueces"), irr_body)

      # ── Advanced Reliability (SEM) ────────────────────────────────────────
      adv_body <- paste0(
        p(private$.tr("The classical coefficients above (\u03B1, \u03C9, GLB, ...) treat the scale's factor structure as either unknown (a single common source) or only exploratorily detected (parallel analysis). When the structure is already known \u2014 from theory or a prior validation \u2014 the separate Advanced Reliability (SEM) analysis lets the user assign items to named factors and fits a confirmatory factor model (via lavaan/semTools) instead, giving structure-specific reliability and validity evidence.", "Los coeficientes cl\u00E1sicos de arriba (\u03B1, \u03C9, GLB, ...) tratan la estructura factorial de la escala como desconocida (una sola fuente com\u00FAn) o solo detectada exploratoriamente (an\u00E1lisis paralelo). Cuando la estructura ya se conoce \u2014 por teor\u00EDa o una validaci\u00F3n previa \u2014 el an\u00E1lisis separado Confiabilidad Avanzada (SEM) permite asignar \u00EDtems a factores nombrados y ajusta en su lugar un modelo factorial confirmatorio (v\u00EDa lavaan/semTools), dando evidencia de confiabilidad y validez espec\u00EDfica a esa estructura.")),
        h4(private$.tr("Exploratory Dimensionality (Parallel Analysis)", "Dimensionalidad Exploratoria (An\u00E1lisis Paralelo)")),
        p(private$.tr("Before trusting a fixed confirmatory structure, parallel analysis (Horn, 1965) asks how many factors the items suggest on their own: it compares the items' actual eigenvalues against the eigenvalues expected from random data of the same size, and suggests a factor count wherever the real eigenvalue still exceeds its random counterpart. This is exploratory and does not know about the structure assigned in the analysis \u2014 a mismatch with the specified number of factors is worth investigating, not automatic proof the specified structure is wrong: theory-driven confirmatory structures legitimately group items in ways a purely data-driven exploratory method may not recover.", "Antes de confiar en una estructura confirmatoria fija, el an\u00E1lisis paralelo (Horn, 1965) pregunta cu\u00E1ntos factores sugieren los \u00EDtems por s\u00ED solos: compara los eigenvalores reales de los \u00EDtems contra los eigenvalores esperados de datos aleatorios del mismo tama\u00F1o, y sugiere un n\u00FAmero de factores donde el eigenvalor real todav\u00EDa supera a su contraparte aleatoria. Esto es exploratorio y no conoce la estructura asignada en el an\u00E1lisis \u2014 una discrepancia con el n\u00FAmero especificado de factores vale la pena investigarla, no es prueba autom\u00E1tica de que la estructura especificada est\u00E9 mal: las estructuras confirmatorias guiadas por teor\u00EDa leg\u00EDtimamente agrupan \u00EDtems de formas que un m\u00E9todo exploratorio puramente guiado por datos puede no recuperar.")),
        h4(private$.tr("Estimator and Missing Data", "Estimador y Datos Faltantes")),
        p(private$.tr("The confirmatory model's estimator depends on item type: continuous items fit via ML by default, or MLR for robustness to non-normality (adjusted standard errors and a scaled \u03C7\u00B2); ordinal items (auto-detected as whole-number values with \u22647 categories, or set explicitly) always fit via WLSMV on their polychoric/tetrachoric correlations, which requires complete cases. Under a robust estimator (MLR or WLSMV), the plain \u03C7\u00B2/CFI/TLI/RMSEA are not the recommended numbers to interpret \u2014 WLSMV's plain versions can even fall outside the [0,1] range \u2014 the scaled/robust versions are. For continuous items with missing values plausibly missing-at-random, Full Information Maximum Likelihood (FIML) uses all available information per case instead of discarding any case outright; it has no equivalent for ordinal/WLSMV items.", "El estimador del modelo confirmatorio depende del tipo de \u00EDtem: los \u00EDtems continuos se ajustan por defecto con ML, o con MLR para robustez a la no normalidad (errores est\u00E1ndar ajustados y un \u03C7\u00B2 escalado); los \u00EDtems ordinales (auto-detectados como valores enteros con \u22647 categor\u00EDas, o fijados expl\u00EDcitamente) siempre se ajustan con WLSMV sobre sus correlaciones polic\u00F3ricas/tetrac\u00F3ricas, lo cual requiere casos completos. Bajo un estimador robusto (MLR o WLSMV), el \u03C7\u00B2/CFI/TLI/RMSEA simples no son los n\u00FAmeros recomendados para interpretar \u2014 las versiones simples de WLSMV pueden incluso caer fuera del rango [0,1] \u2014 las versiones escaladas/robustas s\u00ED lo son. Para \u00EDtems continuos con valores faltantes plausiblemente al azar, la M\u00E1xima Verosimilitud de Informaci\u00F3n Completa (FIML) usa toda la informaci\u00F3n disponible por caso en vez de descartar cualquier caso por completo; no tiene equivalente para \u00EDtems ordinales/WLSMV.")),
        h4(private$.tr("Solution Admissibility", "Admisibilidad de la Soluci\u00F3n")),
        p(private$.tr("Convergence only means the optimizer stopped at some solution; it does not mean that solution is usable. FiabilityLab additionally checks lavaan's own post-estimation check for Heywood cases and non-positive-definite matrices, counts negative residual variances and standardized loadings at or beyond 1, reports the largest latent factor correlation (near/at 1 signals two factors may not be empirically distinct), and \u2014 for ordinal items \u2014 flags item pairs with an empty cell in their contingency table, which makes that pair's polychoric/tetrachoric correlation unstable or inestimable. None of CR, AVE, H, HTMT, or omega hierarchical should be interpreted from a model that fails this check.", "La convergencia solo significa que el optimizador se detuvo en alguna soluci\u00F3n; no significa que esa soluci\u00F3n sea utilizable. FiabilityLab adicionalmente verifica la propia comprobaci\u00F3n posterior a la estimaci\u00F3n de lavaan en busca de casos Heywood y matrices no definidas positivas, cuenta varianzas residuales negativas y cargas estandarizadas iguales o mayores a 1, reporta la mayor correlaci\u00F3n de factor latente (cercana o igual a 1 se\u00F1ala que dos factores podr\u00EDan no ser emp\u00EDricamente distintos), y \u2014 para \u00EDtems ordinales \u2014 marca pares de \u00EDtems con una celda vac\u00EDa en su tabla de contingencia, lo cual hace que la correlaci\u00F3n polic\u00F3rica/tetrac\u00F3rica de ese par sea inestable o inestimable. Ninguno del CR, AVE, H, HTMT, u omega jer\u00E1rquico deber\u00EDa interpretarse a partir de un modelo que falla esta verificaci\u00F3n.")),
        h4(private$.tr("Model Fit", "Ajuste del Modelo")),
        p(private$.tr("Composite Reliability, AVE, and H are only as trustworthy as the confirmatory model they come from. FiabilityLab reports \u03C7\u00B2, CFI, TLI, RMSEA (with 90% CI), and SRMR for the fitted model, following Hu &amp; Bentler's (1999) cutoffs (CFI/TLI \u2265 .95, RMSEA \u2264 .06, SRMR \u2264 .08 for good fit) \u2014 a model with poor fit should be revised (or its structure reconsidered) before its reliability numbers are reported.", "La Confiabilidad Compuesta, el AVE y el H son tan confiables como el modelo confirmatorio del que provienen. FiabilityLab reporta \u03C7\u00B2, CFI, TLI, RMSEA (con IC 95%) y SRMR del modelo ajustado, siguiendo los criterios de Hu &amp; Bentler (1999) (CFI/TLI \u2265 .95, RMSEA \u2264 .06, SRMR \u2264 .08 para buen ajuste) \u2014 un modelo con ajuste pobre deber\u00EDa revisarse (o reconsiderar su estructura) antes de reportar sus cifras de confiabilidad.")),
        h4(private$.tr("Composite Reliability (CR) / \u03C9", "Confiabilidad Compuesta (CR) / \u03C9")),
        p(private$.tr("The proportion of a factor's composite-score variance attributable to its common factor, computed from the confirmatory model's own standardized loadings \u2014 CR (Fornell &amp; Larcker, 1981) and \u03C9 (McDonald, 1999) are the same underlying quantity from two different literatures (marketing/PLS vs. psychometrics), so FiabilityLab reports one number under both names. Unlike Cronbach's \u03B1, it does not assume equal (tau-equivalent) loadings.", "La proporci\u00F3n de la varianza del puntaje compuesto de un factor atribuible a su factor com\u00FAn, calculada a partir de las cargas estandarizadas propias del modelo confirmatorio \u2014 el CR (Fornell &amp; Larcker, 1981) y el \u03C9 (McDonald, 1999) son la misma cantidad subyacente proveniente de dos literaturas distintas (marketing/PLS vs. psicometr\u00EDa), as\u00ED que FiabilityLab reporta un solo n\u00FAmero bajo ambos nombres. A diferencia del Alfa de Cronbach, no asume cargas iguales (tau-equivalencia).")),
        h4("AVE (Average Variance Extracted)"),
        p(private$.tr("The average of the squared standardized loadings of a factor's own items \u2014 the proportion of variance its indicators share with the factor itself, as opposed to error. AVE \u2265 .50 is the field-standard threshold for adequate convergent validity (Fornell &amp; Larcker, 1981); it is a validity index, not a reliability coefficient, and is reported alongside CR/\u03C9 by convention.", "El promedio de las cargas estandarizadas al cuadrado de los propios \u00EDtems de un factor \u2014 la proporci\u00F3n de varianza que sus indicadores comparten con el factor mismo, en contraste con el error. AVE \u2265 .50 es el umbral est\u00E1ndar del campo para validez convergente adecuada (Fornell &amp; Larcker, 1981); es un \u00EDndice de validez, no un coeficiente de confiabilidad, y se reporta junto al CR/\u03C9 por convenci\u00F3n.")),
        h4(private$.tr("Hancock &amp; Mueller's H", "H de Hancock &amp; Mueller")),
        p(private$.tr("An alternative construct-reliability coefficient, H = &Sigma;(\u03BB\u00B2/(1&minus;\u03BB\u00B2)) / [1 + &Sigma;(\u03BB\u00B2/(1&minus;\u03BB\u00B2))], computed from the same standardized loadings as CR/\u03C9 (Hancock &amp; Mueller, 2001). H is monotonically related to each item's own loading in a way CR/\u03C9 is not, making it somewhat less sensitive to adding or removing a single weak indicator \u2014 reported alongside CR/\u03C9, not as a replacement for it.", "Un coeficiente de confiabilidad de constructo alternativo, H = &Sigma;(\u03BB\u00B2/(1&minus;\u03BB\u00B2)) / [1 + &Sigma;(\u03BB\u00B2/(1&minus;\u03BB\u00B2))], calculado a partir de las mismas cargas estandarizadas que el CR/\u03C9 (Hancock &amp; Mueller, 2001). El H se relaciona mon\u00F3tonamente con la carga de cada \u00EDtem de una forma en que el CR/\u03C9 no lo hace, haci\u00E9ndolo algo menos sensible a agregar o quitar un \u00FAnico indicador d\u00E9bil \u2014 se reporta junto al CR/\u03C9, no como su reemplazo.")),
        h4(private$.tr("Reading Standardized Loadings", "Interpretando las Cargas Estandarizadas")),
        p(private$.tr("FiabilityLab's Standardized Loadings plot flags two different problems, not one: a low-positive loading (below .50, a common though not universal minimum) means the item is a weak indicator of its factor and is a candidate for revision or removal. A <b>negative</b> loading is a different problem entirely \u2014 it almost always means the item needs reverse-scoring (its raw values run opposite the rest of the factor, typically because it is worded in the opposite direction from the other items) rather than that it is a bad item; recode it and re-run the analysis before drawing any conclusion about its quality.", "El gr\u00E1fico de Cargas Estandarizadas de FiabilityLab marca dos problemas distintos, no uno: una carga positiva baja (bajo .50, un m\u00EDnimo com\u00FAn aunque no universal) significa que el \u00EDtem es un indicador d\u00E9bil de su factor y es candidato a revisi\u00F3n o eliminaci\u00F3n. Una carga <b>negativa</b> es un problema completamente distinto \u2014 casi siempre significa que el \u00EDtem necesita recodificaci\u00F3n inversa (sus valores brutos corren en sentido opuesto al resto del factor, t\u00EDpicamente porque est\u00E1 redactado en la direcci\u00F3n opuesta a los dem\u00E1s \u00EDtems) y no que sea un mal \u00EDtem; recodif\u00EDquelo y vuelva a correr el an\u00E1lisis antes de sacar cualquier conclusi\u00F3n sobre su calidad.")),
        h4("HTMT (Heterotrait-Monotrait Ratio)"),
        p(private$.tr("A discriminant-validity check between pairs of factors: whether two subscales are empirically distinct rather than measuring the same thing twice. HTMT &gt; .85 signals a discriminant-validity concern \u2014 the classical Fornell-Larcker criterion and cross-loading inspection were shown to miss this in common research situations that HTMT reliably detects (Henseler, Ringle &amp; Sarstedt, 2015). Only computed when 2 or more factors are defined.", "Una verificaci\u00F3n de validez discriminante entre pares de factores: si dos subescalas son emp\u00EDricamente distintas en vez de medir dos veces lo mismo. HTMT &gt; .85 se\u00F1ala una preocupaci\u00F3n de validez discriminante \u2014 se demostr\u00F3 que el criterio cl\u00E1sico de Fornell-Larcker y la inspecci\u00F3n de cargas cruzadas no detectan esto en situaciones de investigaci\u00F3n comunes que el HTMT s\u00ED detecta de forma confiable (Henseler, Ringle &amp; Sarstedt, 2015). Solo se calcula cuando se definen 2 o m\u00E1s factores.")),
        h4(private$.tr("Second-Order Omega Hierarchical", "Omega Jer\u00E1rquico de Segundo Orden")),
        p(private$.tr("When a second-order general factor (G) is specified over 3 or more first-order factors (fewer leaves the higher-order layer statistically unidentified), omega hierarchical is generalized to this confirmatory structure: the proportion of the TOTAL scale's variance attributable specifically to G, net of each subscale's own group-factor variance (McDonald, 1999) \u2014 the same concept the exploratory Omega Hierarchical checkbox in the classical tab estimates via Schmid-Leiman rotation, computed here instead from a user-specified, confirmatory structure.", "Cuando se especifica un factor general de segundo orden (G) sobre 3 o m\u00E1s factores de primer orden (menos deja la capa de orden superior estad\u00EDsticamente no identificada), el omega jer\u00E1rquico se generaliza a esta estructura confirmatoria: la proporci\u00F3n de la varianza de la escala TOTAL atribuible espec\u00EDficamente a G, descontando la varianza de factor de grupo propia de cada subescala (McDonald, 1999) \u2014 el mismo concepto que el checkbox exploratorio Omega Jer\u00E1rquico de la pesta\u00F1a cl\u00E1sica estima v\u00EDa rotaci\u00F3n Schmid-Leiman, calculado aqu\u00ED en cambio a partir de una estructura confirmatoria especificada por el usuario.")),
        p(private$.tr("With exactly 3 first-order factors, the second-order model is mathematically equivalent to (has identical fit as) the correlated-factors model above it \u2014 a second-order factor over exactly 3 lower factors perfectly reproduces their 3 pairwise correlations without adding any constraint. The two fit rows will show identical \u03C7\u00B2/CFI/RMSEA/SRMR in that case; a genuinely testable comparison of whether the general-factor structure fits worse than free correlations among subscales requires 4 or more first-order factors.", "Con exactamente 3 factores de primer orden, el modelo de segundo orden es matem\u00E1ticamente equivalente (tiene el mismo ajuste) al modelo de factores correlacionados de arriba \u2014 un factor de segundo orden sobre exactamente 3 factores inferiores reproduce perfectamente sus 3 correlaciones por pares sin agregar ninguna restricci\u00F3n. Las dos filas de ajuste mostrar\u00E1n \u03C7\u00B2/CFI/RMSEA/SRMR id\u00E9nticos en ese caso; una comparaci\u00F3n genuinamente comprobable de si la estructura de factor general ajusta peor que correlaciones libres entre subescalas requiere 4 o m\u00E1s factores de primer orden.")),
        h4(private$.tr("Model Comparison (Likelihood-Ratio Test)", "Comparaci\u00F3n de Modelos (Prueba de Raz\u00F3n de Verosimilitud)")),
        p(private$.tr("With 4 or more first-order factors, the second-order model is a constrained (nested) version of the freely-correlated one, so their \u03C7\u00B2/df difference is itself \u03C7\u00B2-distributed \u2014 a formal test of whether imposing one general factor costs a significant amount of fit. A significant difference means the general-factor structure fits worse than letting subscales correlate freely, and any general-factor score (or the omega hierarchical value above) should be trusted accordingly less; a non-significant difference supports the second-order structure statistically, though not on its own as evidence that it is the theoretically correct one.", "Con 4 o m\u00E1s factores de primer orden, el modelo de segundo orden es una versi\u00F3n restringida (anidada) del libremente correlacionado, as\u00ED que su diferencia de \u03C7\u00B2/gl es en s\u00ED misma distribuida como \u03C7\u00B2 \u2014 una prueba formal de si imponer un factor general cuesta una cantidad significativa de ajuste. Una diferencia significativa significa que la estructura de factor general ajusta peor que dejar correlacionar libremente a las subescalas, y cualquier puntaje de factor general (o el valor de omega jer\u00E1rquico de arriba) deber\u00EDa confiarse en consecuencia menos; una diferencia no significativa respalda estad\u00EDsticamente la estructura de segundo orden, aunque no por s\u00ED sola como evidencia de que sea la te\u00F3ricamente correcta.")),
        h4(private$.tr("Reliability Due to G", "Confiabilidad Debida a G")),
        p(private$.tr("When a second-order structure is fit, each factor's Reliability Table row also reports its reliability specifically attributable to G \u2014 a different (and typically smaller) quantity than that factor's own CR/\u03C9, since it asks what share of the factor's reliable variance reflects the general trait rather than something specific to the subscale. A factor whose reliability-due-to-G is a small fraction of its own CR/\u03C9 is measuring its specific construct well but would lose most of that reliable variance if folded into a single general-factor or total score.", "Cuando se ajusta una estructura de segundo orden, la fila de cada factor en la Tabla de Confiabilidad tambi\u00E9n reporta su confiabilidad atribuible espec\u00EDficamente a G \u2014 una cantidad distinta (y t\u00EDpicamente menor) que el propio CR/\u03C9 de ese factor, ya que pregunta qu\u00E9 parte de la varianza confiable del factor refleja el rasgo general en vez de algo espec\u00EDfico de la subescala. Un factor cuya confiabilidad-debida-a-G es una fracci\u00F3n peque\u00F1a de su propio CR/\u03C9 est\u00E1 midiendo bien su constructo espec\u00EDfico pero perder\u00EDa la mayor parte de esa varianza confiable si se incorpora a un \u00FAnico puntaje de factor general o total.")),
        h4(private$.tr("Modification Indices \u2014 Interpret Through Theory, Not Automatically", "\u00CDndices de Modificaci\u00F3n \u2014 Interpretar Mediante Teor\u00EDa, No Autom\u00E1ticamente")),
        p(private$.tr("When model fit is not Good, FiabilityLab reports the largest modification indices (MI) \u2014 the expected \u03C7\u00B2 improvement from freeing one additional cross-loading or correlated residual \u2014 as candidates, never as automatic edits. Purely data-driven model modification capitalizes on chance features of the specific sample and may not replicate in a new one (MacCallum, Roznowski &amp; Necowitz, 1992): a modification index only becomes a defensible change once it is justified by the instrument's theoretical structure (does an item plausibly reflect two constructs at once? does a correlated residual reflect known shared method variance, such as two reverse-worded items on the same scale?). Removing an item is only one of several possible responses to poor fit, not the default one \u2014 respecifying the model, or reconsidering whether the theoretical factor structure itself is correct, are equally valid next steps.", "Cuando el ajuste del modelo no es Bueno, FiabilityLab reporta los mayores \u00EDndices de modificaci\u00F3n (MI) \u2014 la mejora esperada en \u03C7\u00B2 al liberar una carga cruzada o un residuo correlacionado adicional \u2014 como candidatos, nunca como ediciones autom\u00E1ticas. La modificaci\u00F3n del modelo guiada puramente por los datos capitaliza sobre caracter\u00EDsticas azarosas de la muestra espec\u00EDfica y puede no replicarse en una nueva (MacCallum, Roznowski &amp; Necowitz, 1992): un \u00EDndice de modificaci\u00F3n solo se convierte en un cambio defendible una vez que se justifica por la estructura te\u00F3rica del instrumento (\u00BFun \u00EDtem refleja de forma plausible dos constructos a la vez? \u00BFun residuo correlacionado refleja varianza de m\u00E9todo compartida conocida, como dos \u00EDtems redactados en reversa en la misma escala?). Eliminar un \u00EDtem es solo una de varias respuestas posibles a un ajuste pobre, no la predeterminada \u2014 reespecificar el modelo, o reconsiderar si la propia estructura factorial te\u00F3rica es correcta, son pasos siguientes igualmente v\u00E1lidos."))
      )
      advanced_html <- sect(private$.tr("Advanced Reliability (SEM)", "Confiabilidad Avanzada (SEM)"), adv_body)

      # ── Measurement Invariance ───────────────────────────────────────────────
      inv_body <- paste0(
        p(private$.tr("Advanced Reliability (SEM) assumes a single population: its confirmatory model, and every coefficient derived from it, describes how the items function on average across everyone in the data. Before comparing group means, subscale scores, or regression coefficients involving a factor across levels of a grouping variable (sex, country, time point, condition, ...), the separate Measurement Invariance analysis checks whether that same measurement model actually holds across those groups \u2014 an observed group difference is only interpretable as a real difference on the construct if the items measure it the same way in each group. This is not just a software design choice: Raykov (2004) develops reliability and invariance evaluation jointly within the same latent-variable framework, and Jak &amp; Jorgensen (2017) formally show that under strong invariance the between-group residual variance vanishes and composite reliability reaches its ceiling (\u03C9 = 1) \u2014 the flip side being that, when invariance fails, a genuine between-group difference the model cannot attribute to the common factor is forced into that residual/error term instead, so a single pooled Omega/CR computed across non-invariant groups is not interpretable as either group's true reliability.", "Confiabilidad Avanzada (SEM) asume una sola poblaci\u00F3n: su modelo confirmatorio, y cada coeficiente derivado de \u00E9l, describe c\u00F3mo funcionan los \u00EDtems en promedio a trav\u00E9s de todos en los datos. Antes de comparar medias de grupo, puntajes de subescala, o coeficientes de regresi\u00F3n que involucren a un factor entre niveles de una variable de agrupaci\u00F3n (sexo, pa\u00EDs, momento temporal, condici\u00F3n, ...), el an\u00E1lisis separado Invariancia de Medida verifica si ese mismo modelo de medici\u00F3n realmente se sostiene entre esos grupos \u2014 una diferencia de grupo observada solo es interpretable como una diferencia real en el constructo si los \u00EDtems lo miden de la misma forma en cada grupo. Esto no es solo una elecci\u00F3n de dise\u00F1o de software: Raykov (2004) desarrolla la evaluaci\u00F3n de confiabilidad e invariancia conjuntamente dentro del mismo marco de variables latentes, y Jak y Jorgensen (2017) muestran formalmente que bajo invariancia fuerte la varianza residual entre grupos se anula y la confiabilidad compuesta alcanza su tope (\u03C9 = 1) \u2014 la otra cara siendo que, cuando la invariancia falla, una diferencia real entre grupos que el modelo no puede atribuir al factor com\u00FAn queda forzada hacia ese t\u00E9rmino residual/de error en su lugar, as\u00ED que un \u00FAnico Omega/CR agrupado calculado entre grupos no invariantes no es interpretable como la confiabilidad verdadera de ninguno de los dos grupos.")),
        h4(private$.tr("The Invariance Sequence", "La Secuencia de Invariancia")),
        p(private$.tr("Four increasingly restrictive multi-group confirmatory models are fit and compared in sequence, each against the model just before it: <b>Configural</b> \u2014 the same items load on the same factors in every group, with everything else free; the minimum requirement for the construct to even be comparable. <b>Metric (weak)</b> \u2014 factor loadings are additionally constrained equal across groups; required before comparing correlations or regression coefficients involving the factor across groups. <b>Scalar (strong)</b> \u2014 item intercepts (or thresholds, for ordinal items) are additionally constrained equal; required before comparing group means or observed scores \u2014 without it, an observed mean difference may reflect item functioning differences rather than a real difference on the construct. <b>Strict</b> \u2014 item residual variances are additionally constrained equal; a stronger, less commonly required condition.", "Se ajustan y comparan en secuencia cuatro modelos confirmatorios multigrupo cada vez m\u00E1s restrictivos, cada uno contra el modelo justo anterior: <b>Configural</b> \u2014 los mismos \u00EDtems cargan sobre los mismos factores en cada grupo, con todo lo dem\u00E1s libre; el requisito m\u00EDnimo para que el constructo sea siquiera comparable. <b>M\u00E9trica (d\u00E9bil)</b> \u2014 las cargas factoriales se restringen adicionalmente a ser iguales entre grupos; requerida antes de comparar correlaciones o coeficientes de regresi\u00F3n que involucren al factor entre grupos. <b>Escalar (fuerte)</b> \u2014 los interceptos de los \u00EDtems (o umbrales, para \u00EDtems ordinales) se restringen adicionalmente a ser iguales; requerida antes de comparar medias de grupo o puntajes observados \u2014 sin ella, una diferencia de medias observada puede reflejar diferencias en el funcionamiento de los \u00EDtems en vez de una diferencia real en el constructo. <b>Estricta</b> \u2014 las varianzas residuales de los \u00EDtems se restringen adicionalmente a ser iguales; una condici\u00F3n m\u00E1s fuerte, requerida con menos frecuencia.")),
        h4(private$.tr("Testing Each Level (LRT and \u0394CFI)", "Probando Cada Nivel (LRT y \u0394CFI)")),
        p(private$.tr("Since each level is nested within the one before it, their \u03C7\u00B2/df difference is itself \u03C7\u00B2-distributed \u2014 a formal likelihood-ratio test (via lavaan::lavTestLRT()) of whether the added restriction costs a significant amount of fit. But the LRT alone becomes hypersensitive to trivial misfit in large samples, so FiabilityLab also reports the change in CFI (\u0394CFI) between consecutive levels and applies the sample-size-robust criterion of Cheung &amp; Rensvold (2002): a restriction is treated as holding if the LRT is non-significant (p \u2265 .05) <i>or</i> \u0394CFI \u2265 -.01 \u2014 either criterion passing is enough, since they are two different ways of detecting the same problem and can disagree in either direction depending on sample size. Schmitt &amp; Kuljanin (2008) review how this sequence is actually applied in practice, including how often each level is tested and reported.", "Como cada nivel est\u00E1 anidado dentro del anterior, su diferencia de \u03C7\u00B2/gl es en s\u00ED misma distribuida como \u03C7\u00B2 \u2014 una prueba formal de raz\u00F3n de verosimilitud (v\u00EDa lavaan::lavTestLRT()) de si la restricci\u00F3n agregada cuesta una cantidad significativa de ajuste. Pero el LRT por s\u00ED solo se vuelve hipersensible a desajustes triviales en muestras grandes, as\u00ED que FiabilityLab tambi\u00E9n reporta el cambio en CFI (\u0394CFI) entre niveles consecutivos y aplica el criterio robusto al tama\u00F1o muestral de Cheung &amp; Rensvold (2002): una restricci\u00F3n se trata como sostenida si el LRT no es significativo (p \u2265 .05) <i>o</i> \u0394CFI \u2265 -.01 \u2014 basta con que uno de los dos criterios se cumpla, ya que son dos formas distintas de detectar el mismo problema y pueden discrepar en cualquier direcci\u00F3n seg\u00FAn el tama\u00F1o muestral. Schmitt y Kuljanin (2008) revisan c\u00F3mo se aplica esta secuencia en la pr\u00E1ctica, incluyendo con qu\u00E9 frecuencia se prueba y reporta cada nivel.")),
        h4(private$.tr("When a Level Does Not Hold: Partial Invariance", "Cuando un Nivel No Se Sostiene: Invariancia Parcial")),
        p(private$.tr("A failed level does not mean the comparison must be abandoned, nor that full invariance should be forced regardless. The standard next step is to test partial invariance \u2014 freeing the constraint for specific items one at a time (via semTools::partialInvariance()/partialInvarianceCat()) to find which items break it, while keeping it for the rest \u2014 following a stepwise procedure that avoids testing stronger restrictions once a weaker one has already failed (Vandenberg &amp; Lance, 2000). A construct can still be meaningfully compared across groups under partial invariance, provided enough items remain invariant and the non-invariant ones are excluded from or flagged in that comparison.", "Un nivel fallido no significa que la comparaci\u00F3n deba abandonarse, ni que la invariancia completa deba forzarse de todas formas. El siguiente paso est\u00E1ndar es probar invariancia parcial \u2014 liberar la restricci\u00F3n para \u00EDtems espec\u00EDficos uno a la vez (v\u00EDa semTools::partialInvariance()/partialInvarianceCat()) para encontrar qu\u00E9 \u00EDtems la rompen, mientras se mantiene para el resto \u2014 siguiendo un procedimiento escalonado que evita probar restricciones m\u00E1s fuertes una vez que una m\u00E1s d\u00E9bil ya fall\u00F3 (Vandenberg &amp; Lance, 2000). Un constructo a\u00FAn puede compararse significativamente entre grupos bajo invariancia parcial, siempre que suficientes \u00EDtems permanezcan invariantes y los no invariantes se excluyan de esa comparaci\u00F3n o se se\u00F1alen en ella."))
      )
      invariance_html <- sect(private$.tr("Measurement Invariance", "Invariancia de Medida"), inv_body)

      # ── Theoretical Foundations ─────────────────────────────────────────────
      found_table <- tbl(
        c(private$.tr("Framework", "Marco te\u00F3rico"), private$.tr("Core idea", "Idea central"), private$.tr("Key sources", "Fuentes clave")),
        list(
          c(private$.tr("Classical Test Theory (CTT)", "Teor\u00EDa Cl\u00E1sica de los Tests (TCT)"),
            "X = T + E", "Cronbach (1951); McDonald (1999); Nunnally &amp; Bernstein (1994)"),
          c(private$.tr("Generalizability Theory", "Teor\u00EDa de la Generalizabilidad"),
            private$.tr("Extends CTT to decompose error into multiple simultaneous facets (raters, occasions, items)", "Extiende la TCT para descomponer el error en m\u00FAltiples facetas simult\u00E1neas (jueces, ocasiones, \u00EDtems)"),
            "Brennan (2001); Shavelson &amp; Webb (1991)"),
          c(private$.tr("Item Response Theory (IRT)", "Teor\u00EDa de Respuesta al \u00CDtem (TRI)"),
            private$.tr("Models the probability of a response as a function of person ability and item parameters", "Modela la probabilidad de una respuesta en funci\u00F3n de la habilidad de la persona y los par\u00E1metros del \u00EDtem"),
            "Embretson &amp; Reise (2000); Baker &amp; Kim (2017)")
        )
      )
      found_body <- paste0(
        found_table,
        h4(private$.tr("Classical Test Theory", "Teor\u00EDa Cl\u00E1sica de los Tests")),
        p(private$.tr("Models every observed score X as the sum of a true score T and random error E. Reliability, in this framework, is defined as the proportion of observed-score variance attributable to T \u2014 every coefficient in the Internal Consistency category above is an estimator of this same quantity, under different assumptions (Cronbach, 1951; McDonald, 1999; Nunnally &amp; Bernstein, 1994).", "Modela toda puntuaci\u00F3n observada X como la suma de una puntuaci\u00F3n verdadera T y un error aleatorio E. La confiabilidad, en este marco, se define como la proporci\u00F3n de la varianza de la puntuaci\u00F3n observada atribuible a T \u2014 cada coeficiente de la categor\u00EDa Internal Consistency de arriba es un estimador de esta misma cantidad, bajo distintos supuestos (Cronbach, 1951; McDonald, 1999; Nunnally &amp; Bernstein, 1994).")),
        h4(private$.tr("Generalizability Theory", "Teor\u00EDa de la Generalizabilidad")),
        p(private$.tr("Extends CTT by decomposing measurement error into several simultaneous sources (facets) \u2014 raters, occasions, items, forms \u2014 instead of treating all error as one undifferentiated term. A G-study estimates the variance from each facet; a D-study then projects reliability for a specific planned measurement design (Brennan, 2001; Shavelson &amp; Webb, 1991). Not yet implemented as a FiabilityLab module (see the roadmap in ARCHITECTURE.md).", "Extiende la TCT descomponiendo el error de medici\u00F3n en varias fuentes simult\u00E1neas (facetas) \u2014 jueces, ocasiones, \u00EDtems, formas \u2014 en vez de tratar todo el error como un \u00FAnico t\u00E9rmino indiferenciado. Un G-study estima la varianza de cada faceta; un D-study luego proyecta la confiabilidad para un dise\u00F1o de medici\u00F3n planificado espec\u00EDfico (Brennan, 2001; Shavelson &amp; Webb, 1991). A\u00FAn no implementado como m\u00F3dulo de FiabilityLab (ver la hoja de ruta en ARCHITECTURE.md).")),
        h4(private$.tr("Item Response Theory", "Teor\u00EDa de Respuesta al \u00CDtem")),
        p(private$.tr("Models the probability of a specific item response as a function of the respondent's ability (or trait level) and the item's own parameters (difficulty, discrimination, and, in some models, guessing) \u2014 a fundamentally different approach from CTT's total-score-variance decomposition (Embretson &amp; Reise, 2000; Baker &amp; Kim, 2017). Referenced here as a theoretical foundation; not yet implemented as a FiabilityLab module.", "Modela la probabilidad de una respuesta espec\u00EDfica a un \u00EDtem en funci\u00F3n de la habilidad (o nivel del rasgo) del respondiente y de los par\u00E1metros propios del \u00EDtem (dificultad, discriminaci\u00F3n y, en algunos modelos, adivinaci\u00F3n) \u2014 un enfoque fundamentalmente distinto de la descomposici\u00F3n de varianza del puntaje total de la TCT (Embretson &amp; Reise, 2000; Baker &amp; Kim, 2017). Referenciada aqu\u00ED como fundamento te\u00F3rico; a\u00FAn no implementada como m\u00F3dulo de FiabilityLab."))
      )
      foundations_html <- sect(private$.tr("Theoretical Foundations", "Fundamentos Te\u00F3ricos"), found_body)

      # ── Common Errors ───────────────────────────────────────────────────────
      err_table <- tbl(
        c(private$.tr("Error", "Error"), private$.tr("Why it's wrong", "Por qu\u00E9 est\u00E1 mal"), private$.tr("What to do instead", "Qu\u00E9 hacer en su lugar")),
        list(
          c(private$.tr("Using Cronbach's \u03B1 on a multidimensional scale", "Usar el \u03B1 de Cronbach en una escala multidimensional"),
            private$.tr("\u03B1 assumes &tau;-equivalence (unidimensionality); with multiple dimensions it can be a misleading estimate", "El \u03B1 asume &tau;-equivalencia (unidimensionalidad); con m\u00FAltiples dimensiones puede ser una estimaci\u00F3n enga\u00F1osa"),
            private$.tr("Compute \u03B1/\u03C9 per subscale, or report \u03C9/\u03C9\u2095 from a fitted multi-factor model (Cronbach, 1951; McDonald, 1999)", "Calcule \u03B1/\u03C9 por subescala, o reporte \u03C9/\u03C9\u2095 de un modelo multi-factor ajustado (Cronbach, 1951; McDonald, 1999)")),
          c(private$.tr("Interpreting Kappa without checking prevalence", "Interpretar el Kappa sin revisar la prevalencia"),
            private$.tr("High raw agreement with low Kappa signals the prevalence paradox, not poor agreement", "Alto acuerdo bruto con Kappa bajo se\u00F1ala la paradoja de prevalencia, no un acuerdo pobre"),
            private$.tr("Report Gwet's AC1/AC2 alongside Kappa (Gwet, 2014)", "Reporte el AC1/AC2 de Gwet junto al Kappa (Gwet, 2014)")),
          c(private$.tr("Confusing reliability with validity", "Confundir confiabilidad con validez"),
            private$.tr("A measure can be highly reliable (consistent) yet not valid (not measuring the intended construct)", "Una medida puede ser muy confiable (consistente) pero no v\u00E1lida (no medir el constructo pretendido)"),
            private$.tr("Reliability is necessary but not sufficient for validity (Nunnally &amp; Bernstein, 1994)", "La confiabilidad es necesaria pero no suficiente para la validez (Nunnally &amp; Bernstein, 1994)")),
          c(private$.tr("Treating Ordinal \u03B1 as interchangeable with raw \u03B1", "Tratar el \u03B1 Ordinal como intercambiable con el \u03B1 bruto"),
            private$.tr("They are different estimators computed on different correlation matrices", "Son estimadores distintos calculados sobre matrices de correlaci\u00F3n distintas"),
            private$.tr("State which one was used, and prefer Ordinal \u03B1 for skewed/ordinal items (Zumbo et al., 2007)", "Indique cu\u00E1l se us\u00F3, y prefiera el \u03B1 Ordinal para \u00EDtems sesgados/ordinales (Zumbo et al., 2007)"))
        )
      )
      errors_html <- sect(private$.tr("Common Errors", "Errores Comunes"), err_table)

      # ── Set content, then hide sections outside the selected category ──────
      self$results$intro$setContent(intro_html)
      self$results$internalConsistency$setContent(internalConsistency_html)
      self$results$interRater$setContent(interRater_html)
      self$results$advanced$setContent(advanced_html)
      self$results$invariance$setContent(invariance_html)
      self$results$foundations$setContent(foundations_html)
      self$results$errors$setContent(errors_html)

      show <- function(name) category == "all" || category == name
      if (!show("internalConsistency")) self$results$internalConsistency$setVisible(FALSE)
      if (!show("interRater"))          self$results$interRater$setVisible(FALSE)
      if (!show("advanced"))            self$results$advanced$setVisible(FALSE)
      if (!show("invariance"))          self$results$invariance$setVisible(FALSE)
      if (!show("foundations"))         self$results$foundations$setVisible(FALSE)
      if (!show("errors"))              self$results$errors$setVisible(FALSE)
    }
  )
)
