
# This file is automatically generated, you probably don't want to edit this

internalConsistencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "internalConsistencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            items = NULL,
            reportLang = "en",
            measureLevel = "auto",
            alpha = TRUE,
            ordinalAlpha = FALSE,
            omega = TRUE,
            omegaHierarchical = FALSE,
            glb = FALSE,
            splitHalf = FALSE,
            guttman = FALSE,
            kr20 = TRUE,
            kr21 = TRUE,
            itemAnalysis = TRUE,
            normality = TRUE,
            bootstrapCi = TRUE,
            bootstrapSamples = 1000,
            checkDimensionality = TRUE,
            checkReliabilityAssumptions = TRUE,
            showPlots = FALSE,
            plotItemDist = TRUE,
            plotItemTotal = TRUE,
            plotScree = FALSE,
            plotStyle = "gray",
            advancedEnable = FALSE,
            secondOrder = FALSE,
            factorName1 = "Factor 1",
            factorItems1 = NULL,
            factorName2 = "Factor 2",
            factorItems2 = NULL,
            factorName3 = "Factor 3",
            factorItems3 = NULL,
            factorName4 = "Factor 4",
            factorItems4 = NULL,
            factorName5 = "Factor 5",
            factorItems5 = NULL, ...) {

            super$initialize(
                package="fiabilitylab",
                name="internalConsistency",
                requiresData=TRUE,
                ...)

            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..measureLevel <- jmvcore::OptionList$new(
                "measureLevel",
                measureLevel,
                options=list(
                    "auto",
                    "dichotomous",
                    "polytomous"),
                default="auto")
            private$..alpha <- jmvcore::OptionBool$new(
                "alpha",
                alpha,
                default=TRUE)
            private$..ordinalAlpha <- jmvcore::OptionBool$new(
                "ordinalAlpha",
                ordinalAlpha,
                default=FALSE)
            private$..omega <- jmvcore::OptionBool$new(
                "omega",
                omega,
                default=TRUE)
            private$..omegaHierarchical <- jmvcore::OptionBool$new(
                "omegaHierarchical",
                omegaHierarchical,
                default=FALSE)
            private$..glb <- jmvcore::OptionBool$new(
                "glb",
                glb,
                default=FALSE)
            private$..splitHalf <- jmvcore::OptionBool$new(
                "splitHalf",
                splitHalf,
                default=FALSE)
            private$..guttman <- jmvcore::OptionBool$new(
                "guttman",
                guttman,
                default=FALSE)
            private$..kr20 <- jmvcore::OptionBool$new(
                "kr20",
                kr20,
                default=TRUE)
            private$..kr21 <- jmvcore::OptionBool$new(
                "kr21",
                kr21,
                default=TRUE)
            private$..itemAnalysis <- jmvcore::OptionBool$new(
                "itemAnalysis",
                itemAnalysis,
                default=TRUE)
            private$..normality <- jmvcore::OptionBool$new(
                "normality",
                normality,
                default=TRUE)
            private$..bootstrapCi <- jmvcore::OptionBool$new(
                "bootstrapCi",
                bootstrapCi,
                default=TRUE)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                default=1000,
                min=100,
                max=10000)
            private$..checkDimensionality <- jmvcore::OptionBool$new(
                "checkDimensionality",
                checkDimensionality,
                default=TRUE)
            private$..checkReliabilityAssumptions <- jmvcore::OptionBool$new(
                "checkReliabilityAssumptions",
                checkReliabilityAssumptions,
                default=TRUE)
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=FALSE)
            private$..plotItemDist <- jmvcore::OptionBool$new(
                "plotItemDist",
                plotItemDist,
                default=TRUE)
            private$..plotItemTotal <- jmvcore::OptionBool$new(
                "plotItemTotal",
                plotItemTotal,
                default=TRUE)
            private$..plotScree <- jmvcore::OptionBool$new(
                "plotScree",
                plotScree,
                default=FALSE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "light",
                    "gray",
                    "linedraw",
                    "greenred",
                    "purpleorange",
                    "bluegreen"),
                default="gray")
            private$..advancedEnable <- jmvcore::OptionBool$new(
                "advancedEnable",
                advancedEnable,
                default=FALSE)
            private$..secondOrder <- jmvcore::OptionBool$new(
                "secondOrder",
                secondOrder,
                default=FALSE)
            private$..factorName1 <- jmvcore::OptionString$new(
                "factorName1",
                factorName1,
                default="Factor 1")
            private$..factorItems1 <- jmvcore::OptionVariables$new(
                "factorItems1",
                factorItems1,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..factorName2 <- jmvcore::OptionString$new(
                "factorName2",
                factorName2,
                default="Factor 2")
            private$..factorItems2 <- jmvcore::OptionVariables$new(
                "factorItems2",
                factorItems2,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..factorName3 <- jmvcore::OptionString$new(
                "factorName3",
                factorName3,
                default="Factor 3")
            private$..factorItems3 <- jmvcore::OptionVariables$new(
                "factorItems3",
                factorItems3,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..factorName4 <- jmvcore::OptionString$new(
                "factorName4",
                factorName4,
                default="Factor 4")
            private$..factorItems4 <- jmvcore::OptionVariables$new(
                "factorItems4",
                factorItems4,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..factorName5 <- jmvcore::OptionString$new(
                "factorName5",
                factorName5,
                default="Factor 5")
            private$..factorItems5 <- jmvcore::OptionVariables$new(
                "factorItems5",
                factorItems5,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..items)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..measureLevel)
            self$.addOption(private$..alpha)
            self$.addOption(private$..ordinalAlpha)
            self$.addOption(private$..omega)
            self$.addOption(private$..omegaHierarchical)
            self$.addOption(private$..glb)
            self$.addOption(private$..splitHalf)
            self$.addOption(private$..guttman)
            self$.addOption(private$..kr20)
            self$.addOption(private$..kr21)
            self$.addOption(private$..itemAnalysis)
            self$.addOption(private$..normality)
            self$.addOption(private$..bootstrapCi)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..checkDimensionality)
            self$.addOption(private$..checkReliabilityAssumptions)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..plotItemDist)
            self$.addOption(private$..plotItemTotal)
            self$.addOption(private$..plotScree)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..advancedEnable)
            self$.addOption(private$..secondOrder)
            self$.addOption(private$..factorName1)
            self$.addOption(private$..factorItems1)
            self$.addOption(private$..factorName2)
            self$.addOption(private$..factorItems2)
            self$.addOption(private$..factorName3)
            self$.addOption(private$..factorItems3)
            self$.addOption(private$..factorName4)
            self$.addOption(private$..factorItems4)
            self$.addOption(private$..factorName5)
            self$.addOption(private$..factorItems5)
        }),
    active = list(
        items = function() private$..items$value,
        reportLang = function() private$..reportLang$value,
        measureLevel = function() private$..measureLevel$value,
        alpha = function() private$..alpha$value,
        ordinalAlpha = function() private$..ordinalAlpha$value,
        omega = function() private$..omega$value,
        omegaHierarchical = function() private$..omegaHierarchical$value,
        glb = function() private$..glb$value,
        splitHalf = function() private$..splitHalf$value,
        guttman = function() private$..guttman$value,
        kr20 = function() private$..kr20$value,
        kr21 = function() private$..kr21$value,
        itemAnalysis = function() private$..itemAnalysis$value,
        normality = function() private$..normality$value,
        bootstrapCi = function() private$..bootstrapCi$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        checkDimensionality = function() private$..checkDimensionality$value,
        checkReliabilityAssumptions = function() private$..checkReliabilityAssumptions$value,
        showPlots = function() private$..showPlots$value,
        plotItemDist = function() private$..plotItemDist$value,
        plotItemTotal = function() private$..plotItemTotal$value,
        plotScree = function() private$..plotScree$value,
        plotStyle = function() private$..plotStyle$value,
        advancedEnable = function() private$..advancedEnable$value,
        secondOrder = function() private$..secondOrder$value,
        factorName1 = function() private$..factorName1$value,
        factorItems1 = function() private$..factorItems1$value,
        factorName2 = function() private$..factorName2$value,
        factorItems2 = function() private$..factorItems2$value,
        factorName3 = function() private$..factorName3$value,
        factorItems3 = function() private$..factorItems3$value,
        factorName4 = function() private$..factorName4$value,
        factorItems4 = function() private$..factorItems4$value,
        factorName5 = function() private$..factorName5$value,
        factorItems5 = function() private$..factorItems5$value),
    private = list(
        ..items = NA,
        ..reportLang = NA,
        ..measureLevel = NA,
        ..alpha = NA,
        ..ordinalAlpha = NA,
        ..omega = NA,
        ..omegaHierarchical = NA,
        ..glb = NA,
        ..splitHalf = NA,
        ..guttman = NA,
        ..kr20 = NA,
        ..kr21 = NA,
        ..itemAnalysis = NA,
        ..normality = NA,
        ..bootstrapCi = NA,
        ..bootstrapSamples = NA,
        ..checkDimensionality = NA,
        ..checkReliabilityAssumptions = NA,
        ..showPlots = NA,
        ..plotItemDist = NA,
        ..plotItemTotal = NA,
        ..plotScree = NA,
        ..plotStyle = NA,
        ..advancedEnable = NA,
        ..secondOrder = NA,
        ..factorName1 = NA,
        ..factorItems1 = NA,
        ..factorName2 = NA,
        ..factorItems2 = NA,
        ..factorName3 = NA,
        ..factorItems3 = NA,
        ..factorName4 = NA,
        ..factorItems4 = NA,
        ..factorName5 = NA,
        ..factorItems5 = NA)
)

internalConsistencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "internalConsistencyResults",
    inherit = jmvcore::Group,
    active = list(
        autoDetectNote = function() private$.items[["autoDetectNote"]],
        sampleAdequacy = function() private$.items[["sampleAdequacy"]],
        mainTable = function() private$.items[["mainTable"]],
        plotComparison = function() private$.items[["plotComparison"]],
        discordanceNote = function() private$.items[["discordanceNote"]],
        bootstrapTable = function() private$.items[["bootstrapTable"]],
        reliabilityAssumptionsTable = function() private$.items[["reliabilityAssumptionsTable"]],
        reliabilityAssumptionsNote = function() private$.items[["reliabilityAssumptionsNote"]],
        normalityTable = function() private$.items[["normalityTable"]],
        dimensionalityNote = function() private$.items[["dimensionalityNote"]],
        itemTable = function() private$.items[["itemTable"]],
        plotItemDist = function() private$.items[["plotItemDist"]],
        plotItemTotal = function() private$.items[["plotItemTotal"]],
        plotScree = function() private$.items[["plotScree"]],
        interpretation = function() private$.items[["interpretation"]],
        advancedFitTable = function() private$.items[["advancedFitTable"]],
        advancedReliabilityTable = function() private$.items[["advancedReliabilityTable"]],
        advancedHtmtTable = function() private$.items[["advancedHtmtTable"]],
        advancedOmegaHNote = function() private$.items[["advancedOmegaHNote"]],
        advancedInterpretation = function() private$.items[["advancedInterpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Internal Consistency")
            self$add(jmvcore::Html$new(
                options=options,
                name="autoDetectNote",
                title="Data Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="sampleAdequacy",
                title="Sample & Data Quality"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mainTable",
                title="Reliability Coefficients",
                rows=0,
                columns=list(
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="applicability", 
                        `title`="Conditions", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotComparison",
                title="Coefficient Comparison",
                width=600,
                height=350,
                renderFun=".plotComparison"))
            self$add(jmvcore::Html$new(
                options=options,
                name="discordanceNote",
                title="Coefficient Discordance"))
            self$add(jmvcore::Table$new(
                options=options,
                name="bootstrapTable",
                title="Bootstrap Confidence Intervals (95%)",
                visible="(bootstrapCi)",
                rows=0,
                columns=list(
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="se_boot", 
                        `title`="Boot SE", 
                        `type`="number", 
                        `format`="zto,digits=3"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="reliabilityAssumptionsTable",
                title="Reliability Assumptions Check",
                visible="(alpha && checkReliabilityAssumptions)",
                rows=0,
                columns=list(
                    list(
                        `name`="assumption", 
                        `title`="Assumption", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text"),
                    list(
                        `name`="p_value", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,digits=4"),
                    list(
                        `name`="verdict", 
                        `title`="Verdict", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="reliabilityAssumptionsNote",
                title="Reliability Assumptions \u2014 What It Means",
                visible="(alpha && checkReliabilityAssumptions)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalityTable",
                title="Item Normality (Shapiro-Wilk)",
                visible="(normality)",
                rows=0,
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="W", 
                        `title`="W", 
                        `type`="number", 
                        `format`="zto,digits=4"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="sig", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="skewness", 
                        `title`="Skewness", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="kurtosis", 
                        `title`="Kurtosis", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="decision", 
                        `title`="Decision", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="dimensionalityNote",
                title="Dimensionality Check",
                visible="(checkDimensionality)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="itemTable",
                title="Item Analysis",
                visible="(itemAnalysis)",
                rows=0,
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="skewness", 
                        `title`="Skew", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="n_unique", 
                        `title`="Options", 
                        `type`="integer"),
                    list(
                        `name`="citc", 
                        `title`="r(item-total)", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="alpha_drop", 
                        `title`="\u03B1 if deleted", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="loading", 
                        `title`="Factor load.", 
                        `type`="number", 
                        `format`="zto,digits=3"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotItemDist",
                title="Item Score Distributions",
                visible="(showPlots && plotItemDist)",
                width=900,
                height=500,
                renderFun=".plotItemDist",
                clearWith=list(
                    "items",
                    "showPlots",
                    "plotItemDist")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotItemTotal",
                title="Item\u2013Total Correlations",
                visible="(showPlots && plotItemTotal)",
                width=700,
                height=400,
                renderFun=".plotItemTotal",
                clearWith=list(
                    "items",
                    "showPlots",
                    "plotItemTotal")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotScree",
                title="Scree Plot (Parallel Analysis)",
                visible="(showPlots && plotScree)",
                width=600,
                height=400,
                renderFun=".plotScree",
                clearWith=list(
                    "items",
                    "showPlots",
                    "plotScree")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Interpretation & Recommendations"))
            self$add(jmvcore::Table$new(
                options=options,
                name="advancedFitTable",
                title="Advanced (SEM): Confirmatory Factor Model Fit",
                visible="(advancedEnable)",
                rows=0,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number", 
                        `format`="zto,digits=2"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="cfi", 
                        `title`="CFI", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="tli", 
                        `title`="TLI", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rmsea", 
                        `title`="RMSEA", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rmsea_ci", 
                        `title`="RMSEA 90% CI", 
                        `type`="text"),
                    list(
                        `name`="srmr", 
                        `title`="SRMR", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="verdict", 
                        `title`="Fit", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="advancedReliabilityTable",
                title="Advanced (SEM): Reliability by Factor",
                visible="(advancedEnable)",
                rows=0,
                columns=list(
                    list(
                        `name`="factor", 
                        `title`="Factor", 
                        `type`="text"),
                    list(
                        `name`="items", 
                        `title`="Items", 
                        `type`="integer"),
                    list(
                        `name`="cr", 
                        `title`="CR / \u03C9", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ave", 
                        `title`="AVE", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="h", 
                        `title`="H", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="advancedHtmtTable",
                title="Advanced (SEM): Discriminant Validity (HTMT)",
                visible="(advancedEnable)",
                rows=0,
                columns=list(
                    list(
                        `name`="factor_a", 
                        `title`="Factor A", 
                        `type`="text"),
                    list(
                        `name`="factor_b", 
                        `title`="Factor B", 
                        `type`="text"),
                    list(
                        `name`="htmt", 
                        `title`="HTMT", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="verdict", 
                        `title`="Verdict", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="advancedOmegaHNote",
                title="Advanced (SEM): Second-Order Omega Hierarchical",
                visible="(advancedEnable && secondOrder)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="advancedInterpretation",
                title="Advanced (SEM): Interpretation & Recommendations",
                visible="(advancedEnable)"))}))

internalConsistencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "internalConsistencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "internalConsistency",
                version = c(1,0,0),
                options = options,
                results = internalConsistencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Internal Consistency
#'
#' 
#' @param data .
#' @param items .
#' @param reportLang .
#' @param measureLevel .
#' @param alpha .
#' @param ordinalAlpha .
#' @param omega .
#' @param omegaHierarchical .
#' @param glb .
#' @param splitHalf .
#' @param guttman .
#' @param kr20 .
#' @param kr21 .
#' @param itemAnalysis .
#' @param normality .
#' @param bootstrapCi .
#' @param bootstrapSamples .
#' @param checkDimensionality .
#' @param checkReliabilityAssumptions .
#' @param showPlots .
#' @param plotItemDist .
#' @param plotItemTotal .
#' @param plotScree .
#' @param plotStyle .
#' @param advancedEnable .
#' @param secondOrder .
#' @param factorName1 .
#' @param factorItems1 .
#' @param factorName2 .
#' @param factorItems2 .
#' @param factorName3 .
#' @param factorItems3 .
#' @param factorName4 .
#' @param factorItems4 .
#' @param factorName5 .
#' @param factorItems5 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$autoDetectNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sampleAdequacy} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mainTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotComparison} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$discordanceNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$bootstrapTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reliabilityAssumptionsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$reliabilityAssumptionsNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normalityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dimensionalityNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$itemTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotItemDist} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotItemTotal} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotScree} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$advancedFitTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$advancedReliabilityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$advancedHtmtTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$advancedOmegaHNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$advancedInterpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mainTable$asDF}
#'
#' \code{as.data.frame(results$mainTable)}
#'
#' @export
internalConsistency <- function(
    data,
    items,
    reportLang = "en",
    measureLevel = "auto",
    alpha = TRUE,
    ordinalAlpha = FALSE,
    omega = TRUE,
    omegaHierarchical = FALSE,
    glb = FALSE,
    splitHalf = FALSE,
    guttman = FALSE,
    kr20 = TRUE,
    kr21 = TRUE,
    itemAnalysis = TRUE,
    normality = TRUE,
    bootstrapCi = TRUE,
    bootstrapSamples = 1000,
    checkDimensionality = TRUE,
    checkReliabilityAssumptions = TRUE,
    showPlots = FALSE,
    plotItemDist = TRUE,
    plotItemTotal = TRUE,
    plotScree = FALSE,
    plotStyle = "gray",
    advancedEnable = FALSE,
    secondOrder = FALSE,
    factorName1 = "Factor 1",
    factorItems1,
    factorName2 = "Factor 2",
    factorItems2,
    factorName3 = "Factor 3",
    factorItems3,
    factorName4 = "Factor 4",
    factorItems4,
    factorName5 = "Factor 5",
    factorItems5) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("internalConsistency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if ( ! missing(factorItems1)) factorItems1 <- jmvcore::resolveQuo(jmvcore::enquo(factorItems1))
    if ( ! missing(factorItems2)) factorItems2 <- jmvcore::resolveQuo(jmvcore::enquo(factorItems2))
    if ( ! missing(factorItems3)) factorItems3 <- jmvcore::resolveQuo(jmvcore::enquo(factorItems3))
    if ( ! missing(factorItems4)) factorItems4 <- jmvcore::resolveQuo(jmvcore::enquo(factorItems4))
    if ( ! missing(factorItems5)) factorItems5 <- jmvcore::resolveQuo(jmvcore::enquo(factorItems5))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL),
            `if`( ! missing(factorItems1), factorItems1, NULL),
            `if`( ! missing(factorItems2), factorItems2, NULL),
            `if`( ! missing(factorItems3), factorItems3, NULL),
            `if`( ! missing(factorItems4), factorItems4, NULL),
            `if`( ! missing(factorItems5), factorItems5, NULL))


    options <- internalConsistencyOptions$new(
        items = items,
        reportLang = reportLang,
        measureLevel = measureLevel,
        alpha = alpha,
        ordinalAlpha = ordinalAlpha,
        omega = omega,
        omegaHierarchical = omegaHierarchical,
        glb = glb,
        splitHalf = splitHalf,
        guttman = guttman,
        kr20 = kr20,
        kr21 = kr21,
        itemAnalysis = itemAnalysis,
        normality = normality,
        bootstrapCi = bootstrapCi,
        bootstrapSamples = bootstrapSamples,
        checkDimensionality = checkDimensionality,
        checkReliabilityAssumptions = checkReliabilityAssumptions,
        showPlots = showPlots,
        plotItemDist = plotItemDist,
        plotItemTotal = plotItemTotal,
        plotScree = plotScree,
        plotStyle = plotStyle,
        advancedEnable = advancedEnable,
        secondOrder = secondOrder,
        factorName1 = factorName1,
        factorItems1 = factorItems1,
        factorName2 = factorName2,
        factorItems2 = factorItems2,
        factorName3 = factorName3,
        factorItems3 = factorItems3,
        factorName4 = factorName4,
        factorItems4 = factorItems4,
        factorName5 = factorName5,
        factorItems5 = factorItems5)

    analysis <- internalConsistencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

