
# This file is automatically generated, you probably don't want to edit this

interRaterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "interRaterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ratings = NULL,
            dataType = NULL,
            kappa = TRUE,
            gwet = TRUE,
            krippendorff = FALSE,
            icc = FALSE,
            kendallW = FALSE,
            reportLang = NULL, ...) {

            super$initialize(
                package="fiabilitylab",
                name="interRater",
                requiresData=TRUE,
                ...)

            private$..ratings <- jmvcore::OptionVariables$new(
                "ratings",
                ratings)
            private$..dataType <- jmvcore::OptionList$new(
                "dataType",
                dataType,
                options=list(
                    "nominal",
                    "ordinal",
                    "continuous"))
            private$..kappa <- jmvcore::OptionBool$new(
                "kappa",
                kappa,
                default=TRUE)
            private$..gwet <- jmvcore::OptionBool$new(
                "gwet",
                gwet,
                default=TRUE)
            private$..krippendorff <- jmvcore::OptionBool$new(
                "krippendorff",
                krippendorff,
                default=FALSE)
            private$..icc <- jmvcore::OptionBool$new(
                "icc",
                icc,
                default=FALSE)
            private$..kendallW <- jmvcore::OptionBool$new(
                "kendallW",
                kendallW,
                default=FALSE)
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"))

            self$.addOption(private$..ratings)
            self$.addOption(private$..dataType)
            self$.addOption(private$..kappa)
            self$.addOption(private$..gwet)
            self$.addOption(private$..krippendorff)
            self$.addOption(private$..icc)
            self$.addOption(private$..kendallW)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        ratings = function() private$..ratings$value,
        dataType = function() private$..dataType$value,
        kappa = function() private$..kappa$value,
        gwet = function() private$..gwet$value,
        krippendorff = function() private$..krippendorff$value,
        icc = function() private$..icc$value,
        kendallW = function() private$..kendallW$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..ratings = NA,
        ..dataType = NA,
        ..kappa = NA,
        ..gwet = NA,
        ..krippendorff = NA,
        ..icc = NA,
        ..kendallW = NA,
        ..reportLang = NA)
)

interRaterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "interRaterResults",
    inherit = jmvcore::Group,
    active = list(
        mainTable = function() private$.items[["mainTable"]],
        recommendations = function() private$.items[["recommendations"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Inter-Rater Agreement")
            self$add(jmvcore::Table$new(
                options=options,
                name="mainTable",
                title="Agreement Coefficients",
                rows=6,
                columns=list(
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="xx.xx"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="xx.xx"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="xx.xx"),
                    list(
                        `name`="p_value", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="xx.xxxx"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="recommendations",
                title="Recommendations"))}))

interRaterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "interRaterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "interRater",
                version = c(1,0,0),
                options = options,
                results = interRaterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Inter-Rater Agreement
#'
#' 
#' @param data .
#' @param ratings .
#' @param dataType .
#' @param kappa .
#' @param gwet .
#' @param krippendorff .
#' @param icc .
#' @param kendallW .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$mainTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$recommendations} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mainTable$asDF}
#'
#' \code{as.data.frame(results$mainTable)}
#'
#' @export
interRater <- function(
    data,
    ratings,
    dataType,
    kappa = TRUE,
    gwet = TRUE,
    krippendorff = FALSE,
    icc = FALSE,
    kendallW = FALSE,
    reportLang) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("interRater requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ratings)) ratings <- jmvcore::resolveQuo(jmvcore::enquo(ratings))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ratings), ratings, NULL))


    options <- interRaterOptions$new(
        ratings = ratings,
        dataType = dataType,
        kappa = kappa,
        gwet = gwet,
        krippendorff = krippendorff,
        icc = icc,
        kendallW = kendallW,
        reportLang = reportLang)

    analysis <- interRaterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

