
# This file is automatically generated, you probably don't want to edit this

internalConsistencyOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "internalConsistencyOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            items = NULL,
            reportLang = "en",
            measureLevel = "auto",
            alpha = TRUE,
            ordinalAlpha = FALSE,
            omega = TRUE,
            omegaHierarchical = FALSE,
            glb = FALSE,
            splitHalf = FALSE,
            guttman = FALSE,
            kr20 = TRUE,
            kr21 = TRUE,
            itemAnalysis = TRUE,
            normality = TRUE,
            bootstrapCi = TRUE,
            bootstrapSamples = 1000,
            checkDimensionality = TRUE,
            showPlots = FALSE,
            plotItemDist = TRUE,
            plotItemTotal = TRUE,
            plotScree = FALSE,
            plotStyle = "gray", ...) {

            super$initialize(
                package="fiabilitylab",
                name="internalConsistency",
                requiresData=TRUE,
                ...)

            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")
            private$..measureLevel <- jmvcore::OptionList$new(
                "measureLevel",
                measureLevel,
                options=list(
                    "auto",
                    "dichotomous",
                    "polytomous"),
                default="auto")
            private$..alpha <- jmvcore::OptionBool$new(
                "alpha",
                alpha,
                default=TRUE)
            private$..ordinalAlpha <- jmvcore::OptionBool$new(
                "ordinalAlpha",
                ordinalAlpha,
                default=FALSE)
            private$..omega <- jmvcore::OptionBool$new(
                "omega",
                omega,
                default=TRUE)
            private$..omegaHierarchical <- jmvcore::OptionBool$new(
                "omegaHierarchical",
                omegaHierarchical,
                default=FALSE)
            private$..glb <- jmvcore::OptionBool$new(
                "glb",
                glb,
                default=FALSE)
            private$..splitHalf <- jmvcore::OptionBool$new(
                "splitHalf",
                splitHalf,
                default=FALSE)
            private$..guttman <- jmvcore::OptionBool$new(
                "guttman",
                guttman,
                default=FALSE)
            private$..kr20 <- jmvcore::OptionBool$new(
                "kr20",
                kr20,
                default=TRUE)
            private$..kr21 <- jmvcore::OptionBool$new(
                "kr21",
                kr21,
                default=TRUE)
            private$..itemAnalysis <- jmvcore::OptionBool$new(
                "itemAnalysis",
                itemAnalysis,
                default=TRUE)
            private$..normality <- jmvcore::OptionBool$new(
                "normality",
                normality,
                default=TRUE)
            private$..bootstrapCi <- jmvcore::OptionBool$new(
                "bootstrapCi",
                bootstrapCi,
                default=TRUE)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                default=1000,
                min=100,
                max=10000)
            private$..checkDimensionality <- jmvcore::OptionBool$new(
                "checkDimensionality",
                checkDimensionality,
                default=TRUE)
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=FALSE)
            private$..plotItemDist <- jmvcore::OptionBool$new(
                "plotItemDist",
                plotItemDist,
                default=TRUE)
            private$..plotItemTotal <- jmvcore::OptionBool$new(
                "plotItemTotal",
                plotItemTotal,
                default=TRUE)
            private$..plotScree <- jmvcore::OptionBool$new(
                "plotScree",
                plotScree,
                default=FALSE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "light",
                    "gray",
                    "linedraw",
                    "greenred",
                    "purpleorange",
                    "bluegreen"),
                default="gray")

            self$.addOption(private$..items)
            self$.addOption(private$..reportLang)
            self$.addOption(private$..measureLevel)
            self$.addOption(private$..alpha)
            self$.addOption(private$..ordinalAlpha)
            self$.addOption(private$..omega)
            self$.addOption(private$..omegaHierarchical)
            self$.addOption(private$..glb)
            self$.addOption(private$..splitHalf)
            self$.addOption(private$..guttman)
            self$.addOption(private$..kr20)
            self$.addOption(private$..kr21)
            self$.addOption(private$..itemAnalysis)
            self$.addOption(private$..normality)
            self$.addOption(private$..bootstrapCi)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..checkDimensionality)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..plotItemDist)
            self$.addOption(private$..plotItemTotal)
            self$.addOption(private$..plotScree)
            self$.addOption(private$..plotStyle)
        }),
    active = list(
        items = function() private$..items$value,
        reportLang = function() private$..reportLang$value,
        measureLevel = function() private$..measureLevel$value,
        alpha = function() private$..alpha$value,
        ordinalAlpha = function() private$..ordinalAlpha$value,
        omega = function() private$..omega$value,
        omegaHierarchical = function() private$..omegaHierarchical$value,
        glb = function() private$..glb$value,
        splitHalf = function() private$..splitHalf$value,
        guttman = function() private$..guttman$value,
        kr20 = function() private$..kr20$value,
        kr21 = function() private$..kr21$value,
        itemAnalysis = function() private$..itemAnalysis$value,
        normality = function() private$..normality$value,
        bootstrapCi = function() private$..bootstrapCi$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        checkDimensionality = function() private$..checkDimensionality$value,
        showPlots = function() private$..showPlots$value,
        plotItemDist = function() private$..plotItemDist$value,
        plotItemTotal = function() private$..plotItemTotal$value,
        plotScree = function() private$..plotScree$value,
        plotStyle = function() private$..plotStyle$value),
    private = list(
        ..items = NA,
        ..reportLang = NA,
        ..measureLevel = NA,
        ..alpha = NA,
        ..ordinalAlpha = NA,
        ..omega = NA,
        ..omegaHierarchical = NA,
        ..glb = NA,
        ..splitHalf = NA,
        ..guttman = NA,
        ..kr20 = NA,
        ..kr21 = NA,
        ..itemAnalysis = NA,
        ..normality = NA,
        ..bootstrapCi = NA,
        ..bootstrapSamples = NA,
        ..checkDimensionality = NA,
        ..showPlots = NA,
        ..plotItemDist = NA,
        ..plotItemTotal = NA,
        ..plotScree = NA,
        ..plotStyle = NA)
)

internalConsistencyResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "internalConsistencyResults",
    inherit = jmvcore::Group,
    active = list(
        autoDetectNote = function() private$.items[["autoDetectNote"]],
        sampleAdequacy = function() private$.items[["sampleAdequacy"]],
        mainTable = function() private$.items[["mainTable"]],
        bootstrapTable = function() private$.items[["bootstrapTable"]],
        normalityTable = function() private$.items[["normalityTable"]],
        dimensionalityNote = function() private$.items[["dimensionalityNote"]],
        itemTable = function() private$.items[["itemTable"]],
        plotItemDist = function() private$.items[["plotItemDist"]],
        plotItemTotal = function() private$.items[["plotItemTotal"]],
        plotScree = function() private$.items[["plotScree"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Internal Consistency")
            self$add(jmvcore::Html$new(
                options=options,
                name="autoDetectNote",
                title="Data Summary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="sampleAdequacy",
                title="Sample & Data Quality"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mainTable",
                title="Reliability Coefficients",
                rows=0,
                columns=list(
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="applicability", 
                        `title`="Conditions", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="bootstrapTable",
                title="Bootstrap Confidence Intervals (95%)",
                visible="(bootstrapCi)",
                rows=0,
                columns=list(
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="se_boot", 
                        `title`="Boot SE", 
                        `type`="number", 
                        `format`="zto,digits=3"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="normalityTable",
                title="Item Normality (Shapiro-Wilk)",
                visible="(normality)",
                rows=0,
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="W", 
                        `title`="W", 
                        `type`="number", 
                        `format`="zto,digits=4"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="sig", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="skewness", 
                        `title`="Skewness", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="kurtosis", 
                        `title`="Kurtosis", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="decision", 
                        `title`="Decision", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="dimensionalityNote",
                title="Dimensionality Check",
                visible="(checkDimensionality)"))
            self$add(jmvcore::Table$new(
                options=options,
                name="itemTable",
                title="Item Analysis",
                visible="(itemAnalysis)",
                rows=0,
                columns=list(
                    list(
                        `name`="item", 
                        `title`="Item", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="skewness", 
                        `title`="Skew", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="n_unique", 
                        `title`="Options", 
                        `type`="integer"),
                    list(
                        `name`="citc", 
                        `title`="r(item-total)", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="alpha_drop", 
                        `title`="\u03B1 if deleted", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="loading", 
                        `title`="Factor load.", 
                        `type`="number", 
                        `format`="zto,digits=3"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotItemDist",
                title="Item Score Distributions",
                visible="(showPlots && plotItemDist)",
                width=900,
                height=500,
                renderFun=".plotItemDist",
                clearWith=list(
                    "items",
                    "showPlots",
                    "plotItemDist")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotItemTotal",
                title="Item\u2013Total Correlations",
                visible="(showPlots && plotItemTotal)",
                width=700,
                height=400,
                renderFun=".plotItemTotal",
                clearWith=list(
                    "items",
                    "showPlots",
                    "plotItemTotal")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotScree",
                title="Scree Plot (Parallel Analysis)",
                visible="(showPlots && plotScree)",
                width=600,
                height=400,
                renderFun=".plotScree",
                clearWith=list(
                    "items",
                    "showPlots",
                    "plotScree")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Interpretation & Recommendations"))}))

internalConsistencyBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "internalConsistencyBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "internalConsistency",
                version = c(1,0,0),
                options = options,
                results = internalConsistencyResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Internal Consistency
#'
#' 
#' @param data .
#' @param items .
#' @param reportLang .
#' @param measureLevel .
#' @param alpha .
#' @param ordinalAlpha .
#' @param omega .
#' @param omegaHierarchical .
#' @param glb .
#' @param splitHalf .
#' @param guttman .
#' @param kr20 .
#' @param kr21 .
#' @param itemAnalysis .
#' @param normality .
#' @param bootstrapCi .
#' @param bootstrapSamples .
#' @param checkDimensionality .
#' @param showPlots .
#' @param plotItemDist .
#' @param plotItemTotal .
#' @param plotScree .
#' @param plotStyle .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$autoDetectNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$sampleAdequacy} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mainTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bootstrapTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$normalityTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dimensionalityNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$itemTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotItemDist} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotItemTotal} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotScree} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mainTable$asDF}
#'
#' \code{as.data.frame(results$mainTable)}
#'
#' @export
internalConsistency <- function(
    data,
    items,
    reportLang = "en",
    measureLevel = "auto",
    alpha = TRUE,
    ordinalAlpha = FALSE,
    omega = TRUE,
    omegaHierarchical = FALSE,
    glb = FALSE,
    splitHalf = FALSE,
    guttman = FALSE,
    kr20 = TRUE,
    kr21 = TRUE,
    itemAnalysis = TRUE,
    normality = TRUE,
    bootstrapCi = TRUE,
    bootstrapSamples = 1000,
    checkDimensionality = TRUE,
    showPlots = FALSE,
    plotItemDist = TRUE,
    plotItemTotal = TRUE,
    plotScree = FALSE,
    plotStyle = "gray") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("internalConsistency requires jmvcore to be installed (restart may be required)")

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL))


    options <- internalConsistencyOptions$new(
        items = items,
        reportLang = reportLang,
        measureLevel = measureLevel,
        alpha = alpha,
        ordinalAlpha = ordinalAlpha,
        omega = omega,
        omegaHierarchical = omegaHierarchical,
        glb = glb,
        splitHalf = splitHalf,
        guttman = guttman,
        kr20 = kr20,
        kr21 = kr21,
        itemAnalysis = itemAnalysis,
        normality = normality,
        bootstrapCi = bootstrapCi,
        bootstrapSamples = bootstrapSamples,
        checkDimensionality = checkDimensionality,
        showPlots = showPlots,
        plotItemDist = plotItemDist,
        plotItemTotal = plotItemTotal,
        plotScree = plotScree,
        plotStyle = plotStyle)

    analysis <- internalConsistencyClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

