
# This file is automatically generated, you probably don't want to edit this

interRaterOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "interRaterOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            ratings = NULL,
            dataType = "auto",
            kappa = TRUE,
            gwet = TRUE,
            krippendorff = TRUE,
            icc = TRUE,
            checkIccAssumptions = TRUE,
            kendallW = FALSE,
            bootstrapCi = TRUE,
            bootstrapSamples = 1000,
            plotStyle = "gray",
            reportLang = NULL, ...) {

            super$initialize(
                package="fiabilitylab",
                name="interRater",
                requiresData=TRUE,
                ...)

            private$..ratings <- jmvcore::OptionVariables$new(
                "ratings",
                ratings)
            private$..dataType <- jmvcore::OptionList$new(
                "dataType",
                dataType,
                options=list(
                    "auto",
                    "nominal",
                    "ordinal",
                    "continuous"),
                default="auto")
            private$..kappa <- jmvcore::OptionBool$new(
                "kappa",
                kappa,
                default=TRUE)
            private$..gwet <- jmvcore::OptionBool$new(
                "gwet",
                gwet,
                default=TRUE)
            private$..krippendorff <- jmvcore::OptionBool$new(
                "krippendorff",
                krippendorff,
                default=TRUE)
            private$..icc <- jmvcore::OptionBool$new(
                "icc",
                icc,
                default=TRUE)
            private$..checkIccAssumptions <- jmvcore::OptionBool$new(
                "checkIccAssumptions",
                checkIccAssumptions,
                default=TRUE)
            private$..kendallW <- jmvcore::OptionBool$new(
                "kendallW",
                kendallW,
                default=FALSE)
            private$..bootstrapCi <- jmvcore::OptionBool$new(
                "bootstrapCi",
                bootstrapCi,
                default=TRUE)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                default=1000,
                min=100,
                max=10000)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "light",
                    "gray",
                    "linedraw",
                    "greenred",
                    "purpleorange",
                    "bluegreen"),
                default="gray")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"))

            self$.addOption(private$..ratings)
            self$.addOption(private$..dataType)
            self$.addOption(private$..kappa)
            self$.addOption(private$..gwet)
            self$.addOption(private$..krippendorff)
            self$.addOption(private$..icc)
            self$.addOption(private$..checkIccAssumptions)
            self$.addOption(private$..kendallW)
            self$.addOption(private$..bootstrapCi)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        ratings = function() private$..ratings$value,
        dataType = function() private$..dataType$value,
        kappa = function() private$..kappa$value,
        gwet = function() private$..gwet$value,
        krippendorff = function() private$..krippendorff$value,
        icc = function() private$..icc$value,
        checkIccAssumptions = function() private$..checkIccAssumptions$value,
        kendallW = function() private$..kendallW$value,
        bootstrapCi = function() private$..bootstrapCi$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        plotStyle = function() private$..plotStyle$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..ratings = NA,
        ..dataType = NA,
        ..kappa = NA,
        ..gwet = NA,
        ..krippendorff = NA,
        ..icc = NA,
        ..checkIccAssumptions = NA,
        ..kendallW = NA,
        ..bootstrapCi = NA,
        ..bootstrapSamples = NA,
        ..plotStyle = NA,
        ..reportLang = NA)
)

interRaterResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "interRaterResults",
    inherit = jmvcore::Group,
    active = list(
        autoDetectNote = function() private$.items[["autoDetectNote"]],
        mainTable = function() private$.items[["mainTable"]],
        plotComparison = function() private$.items[["plotComparison"]],
        discordanceNote = function() private$.items[["discordanceNote"]],
        iccAssumptionsTable = function() private$.items[["iccAssumptionsTable"]],
        iccAssumptionsNote = function() private$.items[["iccAssumptionsNote"]],
        plotDiagnostic = function() private$.items[["plotDiagnostic"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Inter-Rater Agreement")
            self$add(jmvcore::Html$new(
                options=options,
                name="autoDetectNote",
                title="Data Summary"))
            self$add(jmvcore::Table$new(
                options=options,
                name="mainTable",
                title="Agreement Coefficients",
                rows=0,
                columns=list(
                    list(
                        `name`="coefficient", 
                        `title`="Coefficient", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="ci_lower", 
                        `title`="CI Lower", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="ci_upper", 
                        `title`="CI Upper", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="p_value", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,digits=4"),
                    list(
                        `name`="n_boot", 
                        `title`="Boot Replicates Used", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotComparison",
                title="Coefficient Comparison",
                width=600,
                height=350,
                renderFun=".plotComparison",
                visible="(kappa || gwet || krippendorff || icc)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="discordanceNote",
                title="Coefficient Discordance"))
            self$add(jmvcore::Table$new(
                options=options,
                name="iccAssumptionsTable",
                title="ICC Assumptions Check",
                visible="(icc && checkIccAssumptions)",
                rows=0,
                columns=list(
                    list(
                        `name`="assumption", 
                        `title`="Assumption", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text"),
                    list(
                        `name`="p_value", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,digits=4"),
                    list(
                        `name`="verdict", 
                        `title`="Verdict", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="iccAssumptionsNote",
                title="ICC Assumptions \u2014 What It Means",
                visible="(icc && checkIccAssumptions)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotDiagnostic",
                title="Diagnostic Plot",
                width=600,
                height=350,
                renderFun=".plotDiagnostic"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Interpretation & Recommendations"))}))

interRaterBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "interRaterBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "interRater",
                version = c(1,0,0),
                options = options,
                results = interRaterResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Inter-Rater Agreement
#'
#' 
#' @param data .
#' @param ratings .
#' @param dataType .
#' @param kappa .
#' @param gwet .
#' @param krippendorff .
#' @param icc .
#' @param checkIccAssumptions .
#' @param kendallW .
#' @param bootstrapCi .
#' @param bootstrapSamples .
#' @param plotStyle .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$autoDetectNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mainTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plotComparison} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$discordanceNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$iccAssumptionsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$iccAssumptionsNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotDiagnostic} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$mainTable$asDF}
#'
#' \code{as.data.frame(results$mainTable)}
#'
#' @export
interRater <- function(
    data,
    ratings,
    dataType = "auto",
    kappa = TRUE,
    gwet = TRUE,
    krippendorff = TRUE,
    icc = TRUE,
    checkIccAssumptions = TRUE,
    kendallW = FALSE,
    bootstrapCi = TRUE,
    bootstrapSamples = 1000,
    plotStyle = "gray",
    reportLang) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("interRater requires jmvcore to be installed (restart may be required)")

    if ( ! missing(ratings)) ratings <- jmvcore::resolveQuo(jmvcore::enquo(ratings))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(ratings), ratings, NULL))


    options <- interRaterOptions$new(
        ratings = ratings,
        dataType = dataType,
        kappa = kappa,
        gwet = gwet,
        krippendorff = krippendorff,
        icc = icc,
        checkIccAssumptions = checkIccAssumptions,
        kendallW = kendallW,
        bootstrapCi = bootstrapCi,
        bootstrapSamples = bootstrapSamples,
        plotStyle = plotStyle,
        reportLang = reportLang)

    analysis <- interRaterClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

