
# This file is automatically generated, you probably don't want to edit this

measurementInvarianceOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "measurementInvarianceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            group = NULL,
            factors = list(
                list(label="Factor 1", vars=list())),
            itemType = "auto",
            estimator = "auto",
            showPlots = TRUE,
            plotStyle = "gray",
            reportLang = "en", ...) {

            super$initialize(
                package="fiabilitylab",
                name="measurementInvariance",
                requiresData=TRUE,
                ...)

            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..factors <- jmvcore::OptionArray$new(
                "factors",
                factors,
                default=list(
                    list(label="Factor 1", vars=list())),
                template=jmvcore::OptionGroup$new(
                    "factors",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "label",
                            NULL),
                        jmvcore::OptionVariables$new(
                            "vars",
                            NULL,
                            suggested=list(
                                "continuous",
                                "ordinal"),
                            permitted=list(
                                "numeric")))))
            private$..itemType <- jmvcore::OptionList$new(
                "itemType",
                itemType,
                options=list(
                    "auto",
                    "continuous",
                    "ordinal"),
                default="auto")
            private$..estimator <- jmvcore::OptionList$new(
                "estimator",
                estimator,
                options=list(
                    "auto",
                    "ml",
                    "mlr",
                    "wlsmv"),
                default="auto")
            private$..showPlots <- jmvcore::OptionBool$new(
                "showPlots",
                showPlots,
                default=TRUE)
            private$..plotStyle <- jmvcore::OptionList$new(
                "plotStyle",
                plotStyle,
                options=list(
                    "light",
                    "gray",
                    "linedraw",
                    "greenred",
                    "purpleorange",
                    "bluegreen"),
                default="gray")
            private$..reportLang <- jmvcore::OptionList$new(
                "reportLang",
                reportLang,
                options=list(
                    "en",
                    "es"),
                default="en")

            self$.addOption(private$..group)
            self$.addOption(private$..factors)
            self$.addOption(private$..itemType)
            self$.addOption(private$..estimator)
            self$.addOption(private$..showPlots)
            self$.addOption(private$..plotStyle)
            self$.addOption(private$..reportLang)
        }),
    active = list(
        group = function() private$..group$value,
        factors = function() private$..factors$value,
        itemType = function() private$..itemType$value,
        estimator = function() private$..estimator$value,
        showPlots = function() private$..showPlots$value,
        plotStyle = function() private$..plotStyle$value,
        reportLang = function() private$..reportLang$value),
    private = list(
        ..group = NA,
        ..factors = NA,
        ..itemType = NA,
        ..estimator = NA,
        ..showPlots = NA,
        ..plotStyle = NA,
        ..reportLang = NA)
)

measurementInvarianceResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "measurementInvarianceResults",
    inherit = jmvcore::Group,
    active = list(
        groupSummaryTable = function() private$.items[["groupSummaryTable"]],
        invarianceTable = function() private$.items[["invarianceTable"]],
        invarianceNote = function() private$.items[["invarianceNote"]],
        plotInvariance = function() private$.items[["plotInvariance"]],
        plotInvarianceNote = function() private$.items[["plotInvarianceNote"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Measurement Invariance")
            self$add(jmvcore::Table$new(
                options=options,
                name="groupSummaryTable",
                title="Group Sizes",
                rows=0,
                columns=list(
                    list(
                        `name`="level", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="n", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="invarianceTable",
                title="Measurement Invariance Sequence (Nested Model Comparisons)",
                rows=0,
                columns=list(
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number", 
                        `format`="zto,digits=2"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="cfi", 
                        `title`="CFI", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="rmsea", 
                        `title`="RMSEA", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="dchisq", 
                        `title`="\u0394\u03C7\u00B2 (vs. prior)", 
                        `type`="number", 
                        `format`="zto,digits=2"),
                    list(
                        `name`="ddf", 
                        `title`="\u0394df", 
                        `type`="integer"),
                    list(
                        `name`="pvalue", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="dcfi", 
                        `title`="\u0394CFI", 
                        `type`="number", 
                        `format`="zto,digits=3"),
                    list(
                        `name`="verdict", 
                        `title`="Verdict", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="invarianceNote",
                title="Measurement Invariance \u2014 What It Means"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plotInvariance",
                title="Fit Across Invariance Levels",
                width=600,
                height=350,
                renderFun=".plotInvariance",
                visible="(showPlots)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="plotInvarianceNote",
                title="Fit Across Invariance Levels \u2014 What It Means",
                visible="(showPlots)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Interpretation & Recommendations"))}))

measurementInvarianceBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "measurementInvarianceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "fiabilitylab",
                name = "measurementInvariance",
                version = c(1,0,0),
                options = options,
                results = measurementInvarianceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Measurement Invariance
#'
#' 
#' @param data .
#' @param group .
#' @param factors .
#' @param itemType .
#' @param estimator .
#' @param showPlots .
#' @param plotStyle .
#' @param reportLang .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$groupSummaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$invarianceTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$invarianceNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plotInvariance} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plotInvarianceNote} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$groupSummaryTable$asDF}
#'
#' \code{as.data.frame(results$groupSummaryTable)}
#'
#' @export
measurementInvariance <- function(
    data,
    group,
    factors = list(
                list(label="Factor 1", vars=list())),
    itemType = "auto",
    estimator = "auto",
    showPlots = TRUE,
    plotStyle = "gray",
    reportLang = "en") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("measurementInvariance requires jmvcore to be installed (restart may be required)")

    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(group), group, NULL))

    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- measurementInvarianceOptions$new(
        group = group,
        factors = factors,
        itemType = itemType,
        estimator = estimator,
        showPlots = showPlots,
        plotStyle = plotStyle,
        reportLang = reportLang)

    analysis <- measurementInvarianceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

